/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AppearanceSettingsPanel.java
 *
 * Created on 30 Νοε 2011, 7:08:17 μμ
 */
package assignment2.Instability;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class AppearanceSettingsPanel extends javax.swing.JPanel {
	private String	iconPath;
	
	/** Creates new form AppearanceSettingsPanel */
	public AppearanceSettingsPanel() {
		initComponents();
		Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
		
		iconPath = DMSLConnector.getInstance().getClient(false).Evaluate("AcceptanceButton");
		showButtonIcon(adaptiveButton1);
	}
	
	private void showButtonIcon (JButton button) {
		adaptiveButton1.setIcon(null);
		adaptiveButton2.setIcon(null);
		adaptiveButton3.setIcon(null);
		adaptiveButton4.setIcon(null);
		adaptiveButton5.setIcon(null);
		adaptiveButton6.setIcon(null);
		button.setIcon(new ImageIcon(getClass().getResource(iconPath)));
	}	

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new widgets.panel.AdaptivePanel();
        centerPanel = new widgets.panel.AdaptivePanel();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        adaptiveLabel1 = new widgets.label.AdaptiveLabel();
        adaptivePanel4 = new widgets.panel.AdaptivePanel();
        adaptivePanel3 = new widgets.panel.AdaptivePanel();
        adaptiveButton1 = new widgets.button.AdaptiveButton();
        adaptiveButton2 = new widgets.button.AdaptiveButton();
        adaptiveButton3 = new widgets.button.AdaptiveButton();
        adaptiveButton4 = new widgets.button.AdaptiveButton();
        adaptiveButton5 = new widgets.button.AdaptiveButton();
        adaptiveButton6 = new widgets.button.AdaptiveButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adaptiveTextBox1 = new widgets.textbox.AdaptiveTextBox();
        rightPanel = new widgets.panel.AdaptivePanel();
        southPanel = new widgets.panel.AdaptivePanel();

        setLayout(new java.awt.BorderLayout());

        leftPanel.setMaximumSize(new java.awt.Dimension(100, 300));
        leftPanel.setMinimumSize(new java.awt.Dimension(100, 300));
        leftPanel.setPreferredSize(new java.awt.Dimension(100, 300));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        add(leftPanel, java.awt.BorderLayout.WEST);

        centerPanel.setLayout(new java.awt.GridLayout(2, 1));

        adaptivePanel2.setLayout(new java.awt.BorderLayout());

        adaptiveLabel1.setText("Επιλέξτε το θέμα: ");
        adaptivePanel1.add(adaptiveLabel1);

        adaptivePanel2.add(adaptivePanel1, java.awt.BorderLayout.WEST);

        adaptivePanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        adaptivePanel3.setLayout(new java.awt.GridLayout(6, 1, 0, 15));

        adaptiveButton1.setHorizontalAlignment(2);
        adaptiveButton1.setText("Classic");
        adaptiveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton1ActionPerformed(evt);
            }
        });
        adaptivePanel3.add(adaptiveButton1);

        adaptiveButton2.setHorizontalAlignment(2);
        adaptiveButton2.setText("Classic Picture");
        adaptiveButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton2ActionPerformed(evt);
            }
        });
        adaptivePanel3.add(adaptiveButton2);

        adaptiveButton3.setHorizontalAlignment(2);
        adaptiveButton3.setText("Bubble");
        adaptiveButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton3ActionPerformed(evt);
            }
        });
        adaptivePanel3.add(adaptiveButton3);

        adaptiveButton4.setHorizontalAlignment(2);
        adaptiveButton4.setText("Bubble Picture");
        adaptiveButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton4ActionPerformed(evt);
            }
        });
        adaptivePanel3.add(adaptiveButton4);

        adaptiveButton5.setHorizontalAlignment(2);
        adaptiveButton5.setText("Ping Pong");
        adaptiveButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton5ActionPerformed(evt);
            }
        });
        adaptivePanel3.add(adaptiveButton5);

        adaptiveButton6.setHorizontalAlignment(2);
        adaptiveButton6.setText("Ping Pong Picture");
        adaptiveButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton6ActionPerformed(evt);
            }
        });
        adaptivePanel3.add(adaptiveButton6);

        adaptivePanel4.add(adaptivePanel3);

        adaptivePanel2.add(adaptivePanel4, java.awt.BorderLayout.CENTER);

        centerPanel.add(adaptivePanel2);

        adaptiveTextBox1.setColumns(20);
        adaptiveTextBox1.setEditable(false);
        adaptiveTextBox1.setRows(5);
        adaptiveTextBox1.setText("koutsop: Hey! This is a text message!\nmarigianna: Hey ! Yeah I get it!\nkoutsop: Are you getting it without any problems?\nmarigianna: Oh yes. I can read it perfectly.\nkoutsop: ok! Nice to speak to you!");
        jScrollPane1.setViewportView(adaptiveTextBox1);

        centerPanel.add(jScrollPane1);

        add(centerPanel, java.awt.BorderLayout.CENTER);

        rightPanel.setMaximumSize(new java.awt.Dimension(100, 300));
        rightPanel.setMinimumSize(new java.awt.Dimension(100, 300));
        rightPanel.setPreferredSize(new java.awt.Dimension(100, 300));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 436, Short.MAX_VALUE)
        );

        add(rightPanel, java.awt.BorderLayout.EAST);

        southPanel.setMaximumSize(new java.awt.Dimension(300, 100));
        southPanel.setMinimumSize(new java.awt.Dimension(300, 100));
        southPanel.setPreferredSize(new java.awt.Dimension(300, 100));

        javax.swing.GroupLayout southPanelLayout = new javax.swing.GroupLayout(southPanel);
        southPanel.setLayout(southPanelLayout);
        southPanelLayout.setHorizontalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        southPanelLayout.setVerticalGroup(
            southPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        add(southPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

	private void adaptiveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton1ActionPerformed
		showButtonIcon(adaptiveButton1);
	}//GEN-LAST:event_adaptiveButton1ActionPerformed

	private void adaptiveButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton2ActionPerformed
		showButtonIcon(adaptiveButton2);
	}//GEN-LAST:event_adaptiveButton2ActionPerformed

	private void adaptiveButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton3ActionPerformed
		showButtonIcon(adaptiveButton3);
	}//GEN-LAST:event_adaptiveButton3ActionPerformed

	private void adaptiveButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton4ActionPerformed
		showButtonIcon(adaptiveButton4);
	}//GEN-LAST:event_adaptiveButton4ActionPerformed

	private void adaptiveButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton5ActionPerformed
		showButtonIcon(adaptiveButton5);
	}//GEN-LAST:event_adaptiveButton5ActionPerformed

	private void adaptiveButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton6ActionPerformed
		showButtonIcon(adaptiveButton6);
	}//GEN-LAST:event_adaptiveButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.AdaptiveButton adaptiveButton1;
    private widgets.button.AdaptiveButton adaptiveButton2;
    private widgets.button.AdaptiveButton adaptiveButton3;
    private widgets.button.AdaptiveButton adaptiveButton4;
    private widgets.button.AdaptiveButton adaptiveButton5;
    private widgets.button.AdaptiveButton adaptiveButton6;
    private widgets.label.AdaptiveLabel adaptiveLabel1;
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.panel.AdaptivePanel adaptivePanel3;
    private widgets.panel.AdaptivePanel adaptivePanel4;
    private widgets.textbox.AdaptiveTextBox adaptiveTextBox1;
    private widgets.panel.AdaptivePanel centerPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private widgets.panel.AdaptivePanel leftPanel;
    private widgets.panel.AdaptivePanel rightPanel;
    private widgets.panel.AdaptivePanel southPanel;
    // End of variables declaration//GEN-END:variables
}
