/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Call.java
 *
 * Created on 29 Νοε 2011, 1:00:09 πμ
 */
package assignment2.Instability;

import Utility.Utility;
import assignment2.VideoChat;
import java.awt.Dimension;
import java.awt.FlowLayout;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class Call extends javax.swing.JPanel {

	/** Creates new form Call */
	public Call(Dimension parentSize) {
        initComponents();
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
        
        Utility.SetJComponentSize(this, parentSize); 
        
		int size = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("sendVideoImagePanel"));
        Utility.SetJComponentSize(marigiannaPanel, size, size);
        int width   = parentSize.width;
        int height  = (int)(parentSize.height/2.3) - 10; //10 Vertical Gap
        VideoChat chat   = new VideoChat(new Dimension(width, height));
		((FlowLayout)chat.getButtonsPanel().getLayout()).setAlignment(FlowLayout.RIGHT);
        chat.ShowSwapButton(false);
        chat.ShowFullScreenButton(false);
        chat.setVisible(true);
        chatPanel.add(chat);  
		Utility.SetJComponentSize(gapPanel, parentSize.width - size, parentSize.height-height-20);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        callPanel = new widgets.panel.AdaptivePanel();
        gapPanel = new widgets.panel.AdaptivePanel();
        imagePanel = new widgets.panel.AdaptivePanel();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        marigiannaPanel = new widgets.panel.AdaptivePanel();
        chatPanel = new widgets.panel.AdaptivePanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        callPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        callPanel.setLayout(new java.awt.BorderLayout());

        gapPanel.setLayout(new javax.swing.BoxLayout(gapPanel, javax.swing.BoxLayout.LINE_AXIS));
        callPanel.add(gapPanel, java.awt.BorderLayout.CENTER);

        imagePanel.setAlignmentY(0.0F);
        imagePanel.setLayout(new java.awt.BorderLayout());

        adaptivePanel2.setLayout(new javax.swing.BoxLayout(adaptivePanel2, javax.swing.BoxLayout.LINE_AXIS));

        marigiannaPanel.setFunction("marigiannaImg");
        marigiannaPanel.setName("Panel.Content.MarigiannaImage"); // NOI18N

        javax.swing.GroupLayout marigiannaPanelLayout = new javax.swing.GroupLayout(marigiannaPanel);
        marigiannaPanel.setLayout(marigiannaPanelLayout);
        marigiannaPanelLayout.setHorizontalGroup(
            marigiannaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        marigiannaPanelLayout.setVerticalGroup(
            marigiannaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        adaptivePanel2.add(marigiannaPanel);

        imagePanel.add(adaptivePanel2, java.awt.BorderLayout.CENTER);

        callPanel.add(imagePanel, java.awt.BorderLayout.EAST);

        add(callPanel);
        add(chatPanel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.panel.AdaptivePanel callPanel;
    private widgets.panel.AdaptivePanel chatPanel;
    private widgets.panel.AdaptivePanel gapPanel;
    private widgets.panel.AdaptivePanel imagePanel;
    private widgets.panel.AdaptivePanel marigiannaPanel;
    // End of variables declaration//GEN-END:variables
}
