/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HistorySettingsPanel.java
 *
 * Created on 30 Νοε 2011, 5:22:00 μμ
 */
package assignment2.Instability;

import javax.swing.ImageIcon;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class HistorySettingsPanel extends javax.swing.JPanel {
	private boolean showIcon = true;
	private String	iconPath;
	
	/** Creates new form HistorySettingsPanel */
	public HistorySettingsPanel() {
		initComponents();
		
		Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
		
		iconPath = DMSLConnector.getInstance().getClient(false).Evaluate("AcceptanceButton");
        choiceButton.setIcon(new ImageIcon(getClass().getResource(iconPath)));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new widgets.panel.AdaptivePanel();
        centerPanel = new widgets.panel.AdaptivePanel();
        choiceButton = new widgets.button.AdaptiveButton();

        setLayout(new java.awt.BorderLayout());

        leftPanel.setMaximumSize(new java.awt.Dimension(100, 300));
        leftPanel.setMinimumSize(new java.awt.Dimension(100, 300));
        leftPanel.setPreferredSize(new java.awt.Dimension(100, 300));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(leftPanel, java.awt.BorderLayout.WEST);

        centerPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        choiceButton.setFunction("VirtualKeyboardButton");
        choiceButton.setHorizontalAlignment(2);
        choiceButton.setText("Αποθήκευση ιστορικού συνομιλίας");
        choiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choiceButtonActionPerformed(evt);
            }
        });
        centerPanel.add(choiceButton);

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void choiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choiceButtonActionPerformed
		if (showIcon) 
			choiceButton.setIcon(null);
		else
			choiceButton.setIcon(new ImageIcon(getClass().getResource(iconPath)));
		
		showIcon = !showIcon;
	}//GEN-LAST:event_choiceButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.panel.AdaptivePanel centerPanel;
    private widgets.button.AdaptiveButton choiceButton;
    private widgets.panel.AdaptivePanel leftPanel;
    // End of variables declaration//GEN-END:variables
}
