/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NotificationsSettingsPanel.java
 *
 * Created on 30 Νοε 2011, 6:33:35 μμ
 */
package assignment2.Instability;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class NotificationsSettingsPanel extends javax.swing.JPanel {
	private boolean showIcon1 = true;
	private boolean showIcon2 = true;
	private boolean showIcon3 = true;
	private boolean showIcon4 = true;
	private boolean showIcon5 = true;
	private boolean showIcon6 = true;
	private boolean showIcon7 = true;
	private boolean showIcon8 = true;
	private String	iconPath;
	
	/** Creates new form NotificationsSettingsPanel */
	public NotificationsSettingsPanel() {
		initComponents();
		
		Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
		
		iconPath = DMSLConnector.getInstance().getClient(false).Evaluate("AcceptanceButton");
        adaptiveButton1.setIcon(new ImageIcon(getClass().getResource(iconPath)));		
		adaptiveButton2.setIcon(new ImageIcon(getClass().getResource(iconPath)));
		adaptiveButton3.setIcon(new ImageIcon(getClass().getResource(iconPath)));
		adaptiveButton4.setIcon(new ImageIcon(getClass().getResource(iconPath)));
		adaptiveButton5.setIcon(new ImageIcon(getClass().getResource(iconPath)));
		adaptiveButton6.setIcon(new ImageIcon(getClass().getResource(iconPath)));
		adaptiveButton7.setIcon(new ImageIcon(getClass().getResource(iconPath)));
		adaptiveButton8.setIcon(new ImageIcon(getClass().getResource(iconPath)));
	}
	
	private void changeButtonIcon (JButton button, boolean showIcon) {
		if (showIcon) 
			button.setIcon(null);
		else
			button.setIcon(new ImageIcon(getClass().getResource(iconPath)));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new widgets.panel.AdaptivePanel();
        centerPanel = new widgets.panel.AdaptivePanel();
        adaptivePanel22 = new widgets.panel.AdaptivePanel();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        adaptivePanel13 = new widgets.panel.AdaptivePanel();
        adaptivePanel4 = new widgets.panel.AdaptivePanel();
        adaptiveLabel1 = new widgets.label.AdaptiveLabel();
        adaptiveButton7 = new widgets.button.AdaptiveButton();
        adaptiveButton8 = new widgets.button.AdaptiveButton();
        adaptivePanel15 = new widgets.panel.AdaptivePanel();
        adaptivePanel3 = new widgets.panel.AdaptivePanel();
        adaptivePanel10 = new widgets.panel.AdaptivePanel();
        adaptivePanel16 = new widgets.panel.AdaptivePanel();
        adaptiveLabel2 = new widgets.label.AdaptiveLabel();
        adaptiveButton5 = new widgets.button.AdaptiveButton();
        adaptiveButton6 = new widgets.button.AdaptiveButton();
        adaptivePanel17 = new widgets.panel.AdaptivePanel();
        adaptivePanel11 = new widgets.panel.AdaptivePanel();
        adaptivePanel8 = new widgets.panel.AdaptivePanel();
        adaptivePanel18 = new widgets.panel.AdaptivePanel();
        adaptiveLabel3 = new widgets.label.AdaptiveLabel();
        adaptiveButton3 = new widgets.button.AdaptiveButton();
        adaptiveButton4 = new widgets.button.AdaptiveButton();
        adaptivePanel19 = new widgets.panel.AdaptivePanel();
        adaptivePanel6 = new widgets.panel.AdaptivePanel();
        adaptivePanel5 = new widgets.panel.AdaptivePanel();
        adaptivePanel20 = new widgets.panel.AdaptivePanel();
        adaptiveLabel4 = new widgets.label.AdaptiveLabel();
        adaptiveButton2 = new widgets.button.AdaptiveButton();
        adaptivePanel21 = new widgets.panel.AdaptivePanel();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        adaptiveButton1 = new widgets.button.AdaptiveButton();
        rightPanel = new widgets.panel.AdaptivePanel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        leftPanel.setMaximumSize(new java.awt.Dimension(100, 300));
        leftPanel.setMinimumSize(new java.awt.Dimension(100, 300));

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(leftPanel);

        centerPanel.setMaximumSize(new java.awt.Dimension(1000, 600));
        centerPanel.setPreferredSize(new java.awt.Dimension(943, 300));
        centerPanel.setLayout(new java.awt.BorderLayout());

        adaptivePanel22.setLayout(new java.awt.GridLayout(2, 2, 20, 20));

        adaptivePanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        adaptivePanel2.setPreferredSize(new java.awt.Dimension(790, 65));
        adaptivePanel2.setLayout(new java.awt.GridLayout(1, 2));

        adaptivePanel13.setLayout(new java.awt.BorderLayout());

        adaptivePanel4.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        adaptiveLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        adaptiveLabel1.setText("Ειδοποιήσεις Chat");
        adaptivePanel4.add(adaptiveLabel1);

        adaptiveButton7.setHorizontalAlignment(2);
        adaptiveButton7.setText("Αναπαραγωγή ήχου");
        adaptiveButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton7ActionPerformed(evt);
            }
        });
        adaptivePanel4.add(adaptiveButton7);

        adaptiveButton8.setHorizontalAlignment(2);
        adaptiveButton8.setText("Προβολή ειδοποποιήσεων");
        adaptiveButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton8ActionPerformed(evt);
            }
        });
        adaptivePanel4.add(adaptiveButton8);

        adaptivePanel13.add(adaptivePanel4, java.awt.BorderLayout.CENTER);

        adaptivePanel15.setPreferredSize(new java.awt.Dimension(20, 10));

        javax.swing.GroupLayout adaptivePanel15Layout = new javax.swing.GroupLayout(adaptivePanel15);
        adaptivePanel15.setLayout(adaptivePanel15Layout);
        adaptivePanel15Layout.setHorizontalGroup(
            adaptivePanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        adaptivePanel15Layout.setVerticalGroup(
            adaptivePanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        adaptivePanel13.add(adaptivePanel15, java.awt.BorderLayout.WEST);

        adaptivePanel2.add(adaptivePanel13);

        adaptivePanel22.add(adaptivePanel2);

        adaptivePanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        adaptivePanel3.setLayout(new java.awt.GridLayout(1, 2));

        adaptivePanel10.setLayout(new java.awt.BorderLayout());

        adaptivePanel16.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        adaptiveLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        adaptiveLabel2.setText("Ειδοποιήσεις Κλήσης");
        adaptivePanel16.add(adaptiveLabel2);

        adaptiveButton5.setHorizontalAlignment(2);
        adaptiveButton5.setText("Αναπαραγωγή ήχου");
        adaptiveButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton5ActionPerformed(evt);
            }
        });
        adaptivePanel16.add(adaptiveButton5);

        adaptiveButton6.setHorizontalAlignment(2);
        adaptiveButton6.setText("Προβολή ειδοποιήσεων");
        adaptiveButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton6ActionPerformed(evt);
            }
        });
        adaptivePanel16.add(adaptiveButton6);

        adaptivePanel10.add(adaptivePanel16, java.awt.BorderLayout.CENTER);

        adaptivePanel17.setPreferredSize(new java.awt.Dimension(20, 10));

        javax.swing.GroupLayout adaptivePanel17Layout = new javax.swing.GroupLayout(adaptivePanel17);
        adaptivePanel17.setLayout(adaptivePanel17Layout);
        adaptivePanel17Layout.setHorizontalGroup(
            adaptivePanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        adaptivePanel17Layout.setVerticalGroup(
            adaptivePanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        adaptivePanel10.add(adaptivePanel17, java.awt.BorderLayout.WEST);

        adaptivePanel3.add(adaptivePanel10);

        adaptivePanel22.add(adaptivePanel3);

        adaptivePanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        adaptivePanel11.setLayout(new java.awt.GridLayout(1, 2));

        adaptivePanel8.setLayout(new java.awt.BorderLayout());

        adaptivePanel18.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        adaptiveLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        adaptiveLabel3.setText("Ειδοποιήσεις Κλήσης");
        adaptivePanel18.add(adaptiveLabel3);

        adaptiveButton3.setHorizontalAlignment(2);
        adaptiveButton3.setText("Αναπαραγωγή ήχου");
        adaptiveButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton3ActionPerformed(evt);
            }
        });
        adaptivePanel18.add(adaptiveButton3);

        adaptiveButton4.setHorizontalAlignment(2);
        adaptiveButton4.setText("Προβολή ειδοποιήσεων");
        adaptiveButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton4ActionPerformed(evt);
            }
        });
        adaptivePanel18.add(adaptiveButton4);

        adaptivePanel8.add(adaptivePanel18, java.awt.BorderLayout.CENTER);

        adaptivePanel19.setPreferredSize(new java.awt.Dimension(20, 10));

        javax.swing.GroupLayout adaptivePanel19Layout = new javax.swing.GroupLayout(adaptivePanel19);
        adaptivePanel19.setLayout(adaptivePanel19Layout);
        adaptivePanel19Layout.setHorizontalGroup(
            adaptivePanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        adaptivePanel19Layout.setVerticalGroup(
            adaptivePanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        adaptivePanel8.add(adaptivePanel19, java.awt.BorderLayout.WEST);

        adaptivePanel11.add(adaptivePanel8);

        adaptivePanel22.add(adaptivePanel11);

        adaptivePanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        adaptivePanel6.setLayout(new java.awt.GridLayout(1, 2));

        adaptivePanel5.setLayout(new java.awt.BorderLayout());

        adaptivePanel20.setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        adaptiveLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        adaptiveLabel4.setText("Ειδοποιήσεις Εισόδου Επαφών");
        adaptivePanel20.add(adaptiveLabel4);

        adaptiveButton2.setHorizontalAlignment(2);
        adaptiveButton2.setText("Ενεργοποίηση όλων των ειδοποιήσεων");
        adaptiveButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton2ActionPerformed(evt);
            }
        });
        adaptivePanel20.add(adaptiveButton2);

        adaptivePanel5.add(adaptivePanel20, java.awt.BorderLayout.CENTER);

        adaptivePanel21.setPreferredSize(new java.awt.Dimension(20, 10));

        javax.swing.GroupLayout adaptivePanel21Layout = new javax.swing.GroupLayout(adaptivePanel21);
        adaptivePanel21.setLayout(adaptivePanel21Layout);
        adaptivePanel21Layout.setHorizontalGroup(
            adaptivePanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        adaptivePanel21Layout.setVerticalGroup(
            adaptivePanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        adaptivePanel5.add(adaptivePanel21, java.awt.BorderLayout.WEST);

        adaptivePanel6.add(adaptivePanel5);

        adaptivePanel22.add(adaptivePanel6);

        centerPanel.add(adaptivePanel22, java.awt.BorderLayout.CENTER);

        adaptivePanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 20));

        adaptiveButton1.setText("Προβολή ειδοποιήσεων");
        adaptiveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton1ActionPerformed(evt);
            }
        });
        adaptivePanel1.add(adaptiveButton1);

        centerPanel.add(adaptivePanel1, java.awt.BorderLayout.SOUTH);

        add(centerPanel);

        rightPanel.setMaximumSize(new java.awt.Dimension(100, 300));
        rightPanel.setMinimumSize(new java.awt.Dimension(100, 300));
        rightPanel.setPreferredSize(new java.awt.Dimension(100, 300));

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        add(rightPanel);
    }// </editor-fold>//GEN-END:initComponents

	private void adaptiveButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton7ActionPerformed
		changeButtonIcon(adaptiveButton7, showIcon7);
		showIcon7 = ! showIcon7;
	}//GEN-LAST:event_adaptiveButton7ActionPerformed

	private void adaptiveButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton8ActionPerformed
		changeButtonIcon(adaptiveButton8, showIcon8);
		showIcon8 = ! showIcon8;
	}//GEN-LAST:event_adaptiveButton8ActionPerformed

	private void adaptiveButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton5ActionPerformed
		changeButtonIcon(adaptiveButton5, showIcon5);
		showIcon5 = ! showIcon5;
	}//GEN-LAST:event_adaptiveButton5ActionPerformed

	private void adaptiveButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton6ActionPerformed
		changeButtonIcon(adaptiveButton6, showIcon6);
		showIcon6 = ! showIcon6;
	}//GEN-LAST:event_adaptiveButton6ActionPerformed

	private void adaptiveButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton3ActionPerformed
		changeButtonIcon(adaptiveButton3, showIcon3);
		showIcon3 = ! showIcon3;
	}//GEN-LAST:event_adaptiveButton3ActionPerformed

	private void adaptiveButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton4ActionPerformed
		changeButtonIcon(adaptiveButton4, showIcon4);
		showIcon4 = ! showIcon4;
	}//GEN-LAST:event_adaptiveButton4ActionPerformed

	private void adaptiveButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton2ActionPerformed
		changeButtonIcon(adaptiveButton2, showIcon2);
		showIcon2 = ! showIcon2;
	}//GEN-LAST:event_adaptiveButton2ActionPerformed

	private void adaptiveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton1ActionPerformed
		changeButtonIcon(adaptiveButton1, showIcon1);
		showIcon1 = ! showIcon1;
	}//GEN-LAST:event_adaptiveButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.AdaptiveButton adaptiveButton1;
    private widgets.button.AdaptiveButton adaptiveButton2;
    private widgets.button.AdaptiveButton adaptiveButton3;
    private widgets.button.AdaptiveButton adaptiveButton4;
    private widgets.button.AdaptiveButton adaptiveButton5;
    private widgets.button.AdaptiveButton adaptiveButton6;
    private widgets.button.AdaptiveButton adaptiveButton7;
    private widgets.button.AdaptiveButton adaptiveButton8;
    private widgets.label.AdaptiveLabel adaptiveLabel1;
    private widgets.label.AdaptiveLabel adaptiveLabel2;
    private widgets.label.AdaptiveLabel adaptiveLabel3;
    private widgets.label.AdaptiveLabel adaptiveLabel4;
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel10;
    private widgets.panel.AdaptivePanel adaptivePanel11;
    private widgets.panel.AdaptivePanel adaptivePanel13;
    private widgets.panel.AdaptivePanel adaptivePanel15;
    private widgets.panel.AdaptivePanel adaptivePanel16;
    private widgets.panel.AdaptivePanel adaptivePanel17;
    private widgets.panel.AdaptivePanel adaptivePanel18;
    private widgets.panel.AdaptivePanel adaptivePanel19;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.panel.AdaptivePanel adaptivePanel20;
    private widgets.panel.AdaptivePanel adaptivePanel21;
    private widgets.panel.AdaptivePanel adaptivePanel22;
    private widgets.panel.AdaptivePanel adaptivePanel3;
    private widgets.panel.AdaptivePanel adaptivePanel4;
    private widgets.panel.AdaptivePanel adaptivePanel5;
    private widgets.panel.AdaptivePanel adaptivePanel6;
    private widgets.panel.AdaptivePanel adaptivePanel8;
    private widgets.panel.AdaptivePanel centerPanel;
    private widgets.panel.AdaptivePanel leftPanel;
    private widgets.panel.AdaptivePanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
