/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccessibleIM.java
 *
 * Created on 25 Νοε 2011, 12:23:30 μμ
 */
package assignment2;

import pc.MainWindowPC;

/**
 *
 * @author koutsop
 */
public class AccessibleIM extends javax.swing.JPanel {

    /** Creates new form AccessibleIM */
    public AccessibleIM() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuContentsPanel = new widgets.panel.AdaptivePanel();
        menuPanel = new widgets.panel.AdaptivePanel();
        adaptiveButton1 = new widgets.button.AdaptiveButton();
        adaptiveButton2 = new widgets.button.AdaptiveButton();
        settingsButton = new widgets.button.AdaptiveButton();
        startPageButton = new widgets.button.AdaptiveButton();
        adaptiveButton5 = new widgets.button.AdaptiveButton();
        adaptiveButton6 = new widgets.button.AdaptiveButton();
        adaptiveButton7 = new widgets.button.AdaptiveButton();

        setMaximumSize(new java.awt.Dimension(1000, 688));
        setMinimumSize(new java.awt.Dimension(1000, 688));
        setPreferredSize(new java.awt.Dimension(1000, 688));
        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout menuContentsPanelLayout = new javax.swing.GroupLayout(menuContentsPanel);
        menuContentsPanel.setLayout(menuContentsPanelLayout);
        menuContentsPanelLayout.setHorizontalGroup(
            menuContentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        menuContentsPanelLayout.setVerticalGroup(
            menuContentsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        add(menuContentsPanel, java.awt.BorderLayout.CENTER);

        adaptiveButton1.setFunction("MenuButton");
        adaptiveButton1.setText("Accessible IM");
        menuPanel.add(adaptiveButton1);

        adaptiveButton2.setFunction("MenuButton");
        adaptiveButton2.setText("Επιλογές");
        menuPanel.add(adaptiveButton2);

        settingsButton.setFunction("MenuButton");
        settingsButton.setText("Ρυθμίισεις");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        menuPanel.add(settingsButton);

        startPageButton.setFunction("MenuButton");
        startPageButton.setText("Αρχική");
        startPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPageButtonActionPerformed(evt);
            }
        });
        menuPanel.add(startPageButton);

        adaptiveButton5.setText("Έξοδος");
        menuPanel.add(adaptiveButton5);

        adaptiveButton6.setText("adaptiveButton6");
        menuPanel.add(adaptiveButton6);

        adaptiveButton7.setText("adaptiveButton7");
        menuPanel.add(adaptiveButton7);

        add(menuPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {
        MainWindowPC.showPanel(new AdaptableSettingsView());
    }

    private void startPageButtonActionPerformed(java.awt.event.ActionEvent evt) {
        MainWindowPC.showPanel(new Login1());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.AdaptiveButton adaptiveButton1;
    private widgets.button.AdaptiveButton adaptiveButton2;
    private widgets.button.AdaptiveButton adaptiveButton5;
    private widgets.button.AdaptiveButton adaptiveButton6;
    private widgets.button.AdaptiveButton adaptiveButton7;
    private widgets.panel.AdaptivePanel menuContentsPanel;
    private widgets.panel.AdaptivePanel menuPanel;
    private widgets.button.AdaptiveButton settingsButton;
    private widgets.button.AdaptiveButton startPageButton;
    // End of variables declaration//GEN-END:variables
}
