/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Call.java
 *
 * Created on 26 Νοε 2011, 7:16:28 μμ
 */
package assignment2;

import java.awt.Dimension;
import utilities.Adaptation;

/**
 *
 * @author koutsop
 */
public class Call extends javax.swing.JPanel {

    /** Creates new form Call */
    public Call() {
        initComponents();
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
        
        VideoChat chat   = new VideoChat();
        chat.ShowSwapButton(false);
        chat.ShowFullScreenButton(false);
        chat.setVisible(true);
        chatPanel.add(chat);        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        callPanel = new widgets.panel.AdaptivePanel();
        receivePanell = new widgets.panel.AdaptivePanel();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        adaptivePanel3 = new widgets.panel.AdaptivePanel();
        chatPanel = new widgets.panel.AdaptivePanel();

        setLayout(new java.awt.GridLayout(2, 1));

        callPanel.setLayout(new java.awt.BorderLayout());

        receivePanell.setName(""); // NOI18N
        receivePanell.setLayout(new java.awt.GridLayout(1, 3));
        receivePanell.add(adaptivePanel1);

        adaptivePanel2.setFunction("marigiannaImg");
        adaptivePanel2.setName("Panel.Content.MarigiannaImage"); // NOI18N
        receivePanell.add(adaptivePanel2);
        receivePanell.add(adaptivePanel3);

        callPanel.add(receivePanell, java.awt.BorderLayout.CENTER);

        add(callPanel);

        chatPanel.setLayout(new javax.swing.BoxLayout(chatPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(chatPanel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.panel.AdaptivePanel adaptivePanel3;
    private widgets.panel.AdaptivePanel callPanel;
    private widgets.panel.AdaptivePanel chatPanel;
    private widgets.panel.AdaptivePanel receivePanell;
    // End of variables declaration//GEN-END:variables
}
