/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Chat.java
 *
 * Created on 25 Νοε 2011, 11:44:48 πμ
 */
package assignment2;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class Chat extends javax.swing.JPanel {

    /** Creates new form Chat */
    public Chat(Dimension parentSize) {
        initComponents();
        
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
        int contactImgHeight = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("ContactImgHeight"));
		int contactImgWidth = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("ContactImgWidth"));
		int statusImgHeight = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("StatusImgHeight"));
		int statusImgWidth = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("StatusImgWidth"));
		
		assert	contactImgHeight	!= -1 && 
				contactImgWidth		!= -1 && 
				statusImgHeight		!= -1 && 
				statusImgWidth		!= -1;
        
        Utility.SetJComponentSize(avatarPanel, contactImgWidth, contactImgHeight);
        Utility.SetJComponentSize(statusAvatarPanel, statusImgWidth, statusImgHeight);
        Utility.SetJComponentSize(this, parentSize); 
        
        String path = DMSLConnector.getInstance().getClient(false).Evaluate("VideoCallButton");
        videoCallButton.setIcon(new ImageIcon(getClass().getResource(path)));
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("CallButton");
        callButton.setIcon(new ImageIcon(getClass().getResource(path)));
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("SendFileButton");
        sendFileButton.setIcon(new ImageIcon(getClass().getResource(path)));
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("AddButton");
        addButton.setIcon(new ImageIcon(getClass().getResource(path)));  
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("CloseButton");
        closeButton.setIcon(new ImageIcon(getClass().getResource(path)));
        
        System.out.println(this.getPreferredSize());
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendPanel = new widgets.panel.AdaptivePanel();
        chatButtonsPanel = new widgets.panel.AdaptivePanel();
        videoCallButton = new widgets.button.AdaptiveButton();
        callButton = new widgets.button.AdaptiveButton();
        sendFileButton = new widgets.button.AdaptiveButton();
        addButton = new widgets.button.AdaptiveButton();
        closeButton = new widgets.button.AdaptiveButton();
        chatPanel = new widgets.panel.AdaptivePanel();
        sendButonPanel = new widgets.panel.AdaptivePanel();
        sendButton = new widgets.button.AdaptiveButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adaptiveTextBox2 = new widgets.textbox.AdaptiveTextBox();
        contactPanel = new widgets.panel.AdaptivePanel();
        avatarPanel = new widgets.panel.AdaptivePanel();
        statusPanel = new widgets.panel.AdaptivePanel();
        nameLabel = new widgets.label.AdaptiveLabel();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        statusAvatarPanel = new widgets.panel.AdaptivePanel();
        receivePanel = new widgets.panel.AdaptivePanel();
        receiveScrolPane = new javax.swing.JScrollPane();
        adaptiveTextBox1 = new widgets.textbox.AdaptiveTextBox();

        setLayout(new java.awt.BorderLayout(0, 10));

        sendPanel.setLayout(new java.awt.BorderLayout(0, 5));

        chatButtonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        videoCallButton.setFunction("ChatButton");
        chatButtonsPanel.add(videoCallButton);

        callButton.setFunction("ChatButton");
        chatButtonsPanel.add(callButton);

        sendFileButton.setFunction("ChatButton");
        chatButtonsPanel.add(sendFileButton);

        addButton.setFunction("ChatButton");
        chatButtonsPanel.add(addButton);

        closeButton.setFunction("ChatButton");
        chatButtonsPanel.add(closeButton);

        sendPanel.add(chatButtonsPanel, java.awt.BorderLayout.NORTH);

        chatPanel.setLayout(new java.awt.BorderLayout(15, 15));

        sendButonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        sendButton.setFunction("ChatButton");
        sendButton.setText("Send");
        sendButonPanel.add(sendButton);

        chatPanel.add(sendButonPanel, java.awt.BorderLayout.EAST);

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        adaptiveTextBox2.setColumns(20);
        adaptiveTextBox2.setRows(5);
        jScrollPane1.setViewportView(adaptiveTextBox2);

        chatPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        sendPanel.add(chatPanel, java.awt.BorderLayout.CENTER);

        add(sendPanel, java.awt.BorderLayout.PAGE_END);

        contactPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        contactPanel.setMinimumSize(new java.awt.Dimension(125, 100));
        contactPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        avatarPanel.setFunction("ContactImg");
        avatarPanel.setName("ContactPanel.AvatarPanel"); // NOI18N
        contactPanel.add(avatarPanel);

        statusPanel.setLayout(new java.awt.BorderLayout());

        nameLabel.setText("koutsoppoulos Nikolaos: H zwh einai skata");
        statusPanel.add(nameLabel, java.awt.BorderLayout.PAGE_END);

        adaptivePanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        statusAvatarPanel.setFunction("StatusAvailableImg");
        statusAvatarPanel.setName("ContactPanel.StatusAvailablePanel"); // NOI18N
        statusAvatarPanel.setLayout(new javax.swing.BoxLayout(statusAvatarPanel, javax.swing.BoxLayout.LINE_AXIS));
        adaptivePanel1.add(statusAvatarPanel);

        statusPanel.add(adaptivePanel1, java.awt.BorderLayout.PAGE_START);

        contactPanel.add(statusPanel);

        add(contactPanel, java.awt.BorderLayout.PAGE_START);

        receivePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        receivePanel.setLayout(new javax.swing.BoxLayout(receivePanel, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveTextBox1.setColumns(20);
        adaptiveTextBox1.setEditable(false);
        adaptiveTextBox1.setRows(5);
        adaptiveTextBox1.setText("koutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu\nkoutsop:   Bariemai\nkoutsop1: Kai egw polu");
        receiveScrolPane.setViewportView(adaptiveTextBox1);

        receivePanel.add(receiveScrolPane);

        add(receivePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.textbox.AdaptiveTextBox adaptiveTextBox1;
    private widgets.textbox.AdaptiveTextBox adaptiveTextBox2;
    private widgets.button.AdaptiveButton addButton;
    private widgets.panel.AdaptivePanel avatarPanel;
    private widgets.button.AdaptiveButton callButton;
    private widgets.panel.AdaptivePanel chatButtonsPanel;
    private widgets.panel.AdaptivePanel chatPanel;
    private widgets.button.AdaptiveButton closeButton;
    private widgets.panel.AdaptivePanel contactPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private widgets.label.AdaptiveLabel nameLabel;
    private widgets.panel.AdaptivePanel receivePanel;
    private javax.swing.JScrollPane receiveScrolPane;
    private widgets.panel.AdaptivePanel sendButonPanel;
    private widgets.button.AdaptiveButton sendButton;
    private widgets.button.AdaptiveButton sendFileButton;
    private widgets.panel.AdaptivePanel sendPanel;
    private widgets.panel.AdaptivePanel statusAvatarPanel;
    private widgets.panel.AdaptivePanel statusPanel;
    private widgets.button.AdaptiveButton videoCallButton;
    // End of variables declaration//GEN-END:variables
}
