/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on 21 Νοε 2011, 10:15:04 μμ
 */
package assignment2;

import pc.MainWindowPC;
import utilities.Adaptation;

/**
 *
 * @author koutsop
 */
public class Login extends javax.swing.JPanel {

    /** Creates new form Login */
    public Login() {
        initComponents();
        /*Update specific components so as to impose specific rules (both methods take as argument
         the  main container/placeholder the holds all the widgets placed into the UI. This concept
         is similar to the HTML <body> element) */
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
        this.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usernameLabel = new widgets.label.AdaptiveLabel();
        usernameTextField = new widgets.textfield.AdaptiveTextField();
        passwordLabel = new widgets.label.AdaptiveLabel();
        passwordTextField = new widgets.textfield.AdaptiveTextField();
        horizontallyLimitedAdaptivePanel4 = new widgets.panel.HorizontallyLimitedAdaptivePanel();
        rememberPassword = new widgets.checkbox.AdaptiveCheckBox();
        horizontallyLimitedAdaptivePanel3 = new widgets.panel.HorizontallyLimitedAdaptivePanel();
        signInButton = new widgets.button.AdaptiveButton();
        horizontallyLimitedAdaptivePanel2 = new widgets.panel.HorizontallyLimitedAdaptivePanel();
        adaptiveLink1 = new widgets.link.AdaptiveLink();
        horizontallyLimitedAdaptivePanel1 = new widgets.panel.HorizontallyLimitedAdaptivePanel();
        adaptiveLink2 = new widgets.link.AdaptiveLink();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        usernameLabel.setFunction("LoginLabel");
        usernameLabel.setText("Username:");
        add(usernameLabel);

        usernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextFieldActionPerformed(evt);
            }
        });
        add(usernameTextField);

        passwordLabel.setFunction("LoginLabel");
        passwordLabel.setText("Password:");
        add(passwordLabel);
        add(passwordTextField);

        horizontallyLimitedAdaptivePanel4.setBackground(new java.awt.Color(255, 255, 255));
        add(horizontallyLimitedAdaptivePanel4);

        rememberPassword.setText("Remember Password");
        add(rememberPassword);

        horizontallyLimitedAdaptivePanel3.setBackground(new java.awt.Color(255, 255, 255));
        add(horizontallyLimitedAdaptivePanel3);

        signInButton.setText("Sign In");
        signInButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInButtonActionPerformed(evt);
            }
        });
        add(signInButton);

        horizontallyLimitedAdaptivePanel2.setBackground(new java.awt.Color(255, 255, 255));
        add(horizontallyLimitedAdaptivePanel2);

        adaptiveLink1.setText("Forgot your password");
        add(adaptiveLink1);

        horizontallyLimitedAdaptivePanel1.setBackground(new java.awt.Color(255, 255, 255));
        add(horizontallyLimitedAdaptivePanel1);

        adaptiveLink2.setText("Don't have an account");
        add(adaptiveLink2);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextFieldActionPerformed

    private void signInButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInButtonActionPerformed
        AdaptableIMView im = new AdaptableIMView();       
        MainWindowPC.showPanel(im);
    }//GEN-LAST:event_signInButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.link.AdaptiveLink adaptiveLink1;
    private widgets.link.AdaptiveLink adaptiveLink2;
    private widgets.panel.HorizontallyLimitedAdaptivePanel horizontallyLimitedAdaptivePanel1;
    private widgets.panel.HorizontallyLimitedAdaptivePanel horizontallyLimitedAdaptivePanel2;
    private widgets.panel.HorizontallyLimitedAdaptivePanel horizontallyLimitedAdaptivePanel3;
    private widgets.panel.HorizontallyLimitedAdaptivePanel horizontallyLimitedAdaptivePanel4;
    private widgets.label.AdaptiveLabel passwordLabel;
    private widgets.textfield.AdaptiveTextField passwordTextField;
    private widgets.checkbox.AdaptiveCheckBox rememberPassword;
    private widgets.button.AdaptiveButton signInButton;
    private widgets.label.AdaptiveLabel usernameLabel;
    private widgets.textfield.AdaptiveTextField usernameTextField;
    // End of variables declaration//GEN-END:variables
}
