/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NoDisabilityMainView.java
 *
 * Created on 23 Νοε 2011, 3:56:11 μμ
 */
package assignment2.NoDisability;

import assignment2.Contact;

/**
 *
 * @author koutsop
 */
public class NoDisabilityMainView extends javax.swing.JPanel {

    /** Creates new form NoDisabilityMainView */
    public NoDisabilityMainView() {
        initComponents();
		AddContacts();
    }
	
	private void AddContacts () {
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new widgets.panel.AdaptivePanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contactsPanel = new widgets.panel.AdaptivePanel();
        menuPanel = new widgets.panel.AdaptivePanel();
        adaptiveButton1 = new widgets.button.AdaptiveButton();
        adaptiveButton2 = new widgets.button.AdaptiveButton();
        adaptiveButton3 = new widgets.button.AdaptiveButton();
        adaptiveButton4 = new widgets.button.AdaptiveButton();
        contentPanel = new widgets.panel.AdaptivePanel();
        adaptiveButton11 = new widgets.button.AdaptiveButton();

        setMaximumSize(new java.awt.Dimension(1000, 688));
        setMinimumSize(new java.awt.Dimension(1000, 688));
        setPreferredSize(new java.awt.Dimension(1000, 688));
        setLayout(new java.awt.BorderLayout());

        leftPanel.setLayout(new javax.swing.BoxLayout(leftPanel, javax.swing.BoxLayout.PAGE_AXIS));

        contactsPanel.setLayout(new javax.swing.BoxLayout(contactsPanel, javax.swing.BoxLayout.PAGE_AXIS));
        jScrollPane1.setViewportView(contactsPanel);

        leftPanel.add(jScrollPane1);

        add(leftPanel, java.awt.BorderLayout.LINE_START);

        menuPanel.setLayout(new javax.swing.BoxLayout(menuPanel, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveButton1.setText("adaptiveButton1");
        menuPanel.add(adaptiveButton1);

        adaptiveButton2.setText("adaptiveButton2");
        menuPanel.add(adaptiveButton2);

        adaptiveButton3.setText("adaptiveButton3");
        menuPanel.add(adaptiveButton3);

        adaptiveButton4.setText("adaptiveButton4");
        menuPanel.add(adaptiveButton4);

        add(menuPanel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveButton11.setText("adaptiveButton11");
        contentPanel.add(adaptiveButton11);

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.AdaptiveButton adaptiveButton1;
    private widgets.button.AdaptiveButton adaptiveButton11;
    private widgets.button.AdaptiveButton adaptiveButton2;
    private widgets.button.AdaptiveButton adaptiveButton3;
    private widgets.button.AdaptiveButton adaptiveButton4;
    private widgets.panel.AdaptivePanel contactsPanel;
    private widgets.panel.AdaptivePanel contentPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private widgets.panel.AdaptivePanel leftPanel;
    private widgets.panel.AdaptivePanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
