/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProfileCreation.java
 *
 * Created on 21 Νοε 2011, 9:00:27 μμ
 */
package assignment2.NoDisability;

import assignment2.Login1;
import javax.swing.ImageIcon;
import pc.MainWindowPC;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class ProfileCreation extends javax.swing.JPanel {
   

    /** Creates new form ProfileCreation */
   public ProfileCreation() {
    
		initComponents();
		Adaptation.automaticallySetRuntime(this);
		Adaptation.automaticallyAdapt(this);

		String path = DMSLConnector.getInstance().getClient(false).Evaluate("RefreshButton");
		refreshButton.setIcon(new ImageIcon(getClass().getResource(path)));

		path = DMSLConnector.getInstance().getClient(false).Evaluate("ListenButton");
		listenButton.setIcon(new ImageIcon(getClass().getResource(path)));

		path = DMSLConnector.getInstance().getClient(false).Evaluate("HelpButton");
		helpButton.setIcon(new ImageIcon(getClass().getResource(path)));


		path = DMSLConnector.getInstance().getClient(false).Evaluate("CancelButton");
		cancelButton.setIcon(new ImageIcon(getClass().getResource(path)));

		path = DMSLConnector.getInstance().getClient(false).Evaluate("AcceptanceButton");
		acceptanceButton.setIcon(new ImageIcon(getClass().getResource(path)));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adaptiveLabel5 = new widgets.label.AdaptiveLabel();
        adaptiveComboBox1 = new widgets.combobox.AdaptiveComboBox();
        adaptiveLabel7 = new widgets.label.AdaptiveLabel();
        adaptiveComboBox2 = new widgets.combobox.AdaptiveComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel = new widgets.panel.AdaptivePanel();
        profileDataPanel = new widgets.panel.AdaptivePanel();
        adaptivePanel14 = new widgets.panel.AdaptivePanel();
        adaptiveLabel1 = new widgets.label.AdaptiveLabel();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        adaptiveTextField1 = new widgets.textfield.AdaptiveTextField();
        adaptivePanel15 = new widgets.panel.AdaptivePanel();
        adaptiveLabel2 = new widgets.label.AdaptiveLabel();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        adaptiveTextField2 = new widgets.textfield.AdaptiveTextField();
        adaptivePanel16 = new widgets.panel.AdaptivePanel();
        adaptiveLabel3 = new widgets.label.AdaptiveLabel();
        adaptivePanel3 = new widgets.panel.AdaptivePanel();
        adaptiveTextField3 = new widgets.textfield.AdaptiveTextField();
        adaptivePanel17 = new widgets.panel.AdaptivePanel();
        adaptiveLabel4 = new widgets.label.AdaptiveLabel();
        adaptivePanel4 = new widgets.panel.AdaptivePanel();
        adaptiveComboBox3 = new widgets.combobox.AdaptiveComboBox();
        adaptiveComboBox4 = new widgets.combobox.AdaptiveComboBox();
        adaptiveComboBox5 = new widgets.combobox.AdaptiveComboBox();
        adaptivePanel21 = new widgets.panel.AdaptivePanel();
        adaptiveLabel6 = new widgets.label.AdaptiveLabel();
        adaptivePanel5 = new widgets.panel.AdaptivePanel();
        adaptiveComboBox9 = new widgets.combobox.AdaptiveComboBox();
        adaptivePanel22 = new widgets.panel.AdaptivePanel();
        adaptiveLabel8 = new widgets.label.AdaptiveLabel();
        adaptivePanel6 = new widgets.panel.AdaptivePanel();
        adaptiveComboBox6 = new widgets.combobox.AdaptiveComboBox();
        adaptivePanel23 = new widgets.panel.AdaptivePanel();
        adaptiveLabel9 = new widgets.label.AdaptiveLabel();
        adaptivePanel7 = new widgets.panel.AdaptivePanel();
        adaptiveTextField7 = new widgets.textfield.AdaptiveTextField();
        adaptivePanel24 = new widgets.panel.AdaptivePanel();
        adaptiveLabel10 = new widgets.label.AdaptiveLabel();
        adaptivePanel8 = new widgets.panel.AdaptivePanel();
        adaptiveComboBox7 = new widgets.combobox.AdaptiveComboBox();
        adaptivePanel25 = new widgets.panel.AdaptivePanel();
        adaptiveLabel11 = new widgets.label.AdaptiveLabel();
        adaptivePanel9 = new widgets.panel.AdaptivePanel();
        adaptiveTextField9 = new widgets.textfield.AdaptiveTextField();
        adaptivePanel13 = new widgets.panel.AdaptivePanel();
        adaptiveLabel19 = new widgets.label.AdaptiveLabel();
        adaptivePanel27 = new widgets.panel.AdaptivePanel();
        adaptiveComboBox8 = new widgets.combobox.AdaptiveComboBox();
        adaptivePanel26 = new widgets.panel.AdaptivePanel();
        adaptiveLabel12 = new widgets.label.AdaptiveLabel();
        adaptivePanel10 = new widgets.panel.AdaptivePanel();
        adaptiveTextField13 = new widgets.textfield.AdaptiveTextField();
        adaptivePanel20 = new widgets.panel.AdaptivePanel();
        adaptiveLabel16 = new widgets.label.AdaptiveLabel();
        adaptivePanel11 = new widgets.panel.AdaptivePanel();
        adaptiveTextField11 = new widgets.textfield.AdaptiveTextField();
        adaptivePanel19 = new widgets.panel.AdaptivePanel();
        adaptiveLabel17 = new widgets.label.AdaptiveLabel();
        adaptivePanel12 = new widgets.panel.AdaptivePanel();
        adaptiveTextField12 = new widgets.textfield.AdaptiveTextField();
        adaptivePanel28 = new widgets.panel.AdaptivePanel();
        adaptivePanel34 = new widgets.panel.AdaptivePanel();
        adaptivePanel35 = new widgets.panel.AdaptivePanel();
        adaptivePanel18 = new widgets.panel.AdaptivePanel();
        refreshButton = new widgets.button.AdaptiveButton();
        listenButton = new widgets.button.AdaptiveButton();
        helpButton = new widgets.button.AdaptiveButton();
        adaptivePanel29 = new widgets.panel.AdaptivePanel();
        adaptiveLabel14 = new widgets.label.AdaptiveLabel();
        adaptivePanel30 = new widgets.panel.AdaptivePanel();
        adaptiveTextField4 = new widgets.textfield.AdaptiveTextField();
        buttonData = new widgets.panel.AdaptivePanel();
        adaptivePanel31 = new widgets.panel.AdaptivePanel();
        acceptanceButton = new widgets.button.AdaptiveButton();
        adaptivePanel33 = new widgets.panel.AdaptivePanel();
        cancelButton = new widgets.button.AdaptiveButton();
        adaptivePanel32 = new widgets.panel.AdaptivePanel();
        eastPanel = new widgets.panel.AdaptivePanel();
        westPanel = new widgets.panel.AdaptivePanel();
        topPanel = new widgets.panel.AdaptivePanel();
        adaptiveLabel13 = new widgets.label.AdaptiveLabel();

        adaptiveLabel5.setText("adaptiveLabel5");

        adaptiveLabel7.setText("adaptiveLabel7");

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        contentPanel.setLayout(new java.awt.BorderLayout());

        profileDataPanel.setLayout(new java.awt.GridLayout(16, 2, 0, 10));

        adaptivePanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel1.setText("Όνομα");
        adaptivePanel14.add(adaptiveLabel1);

        profileDataPanel.add(adaptivePanel14);

        adaptivePanel1.setLayout(new javax.swing.BoxLayout(adaptivePanel1, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveTextField1.setMaximumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField1.setMinimumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField1.setPreferredSize(new java.awt.Dimension(200, 40));
        adaptivePanel1.add(adaptiveTextField1);

        profileDataPanel.add(adaptivePanel1);

        adaptivePanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel2.setText("Επώνυμο");
        adaptivePanel15.add(adaptiveLabel2);

        profileDataPanel.add(adaptivePanel15);

        adaptivePanel2.setLayout(new javax.swing.BoxLayout(adaptivePanel2, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveTextField2.setMaximumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField2.setMinimumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField2.setPreferredSize(new java.awt.Dimension(200, 40));
        adaptivePanel2.add(adaptiveTextField2);

        profileDataPanel.add(adaptivePanel2);

        adaptivePanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel3.setText("Ε-mail");
        adaptivePanel16.add(adaptiveLabel3);

        profileDataPanel.add(adaptivePanel16);

        adaptivePanel3.setLayout(new javax.swing.BoxLayout(adaptivePanel3, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveTextField3.setMaximumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField3.setMinimumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField3.setPreferredSize(new java.awt.Dimension(200, 40));
        adaptivePanel3.add(adaptiveTextField3);

        profileDataPanel.add(adaptivePanel3);

        adaptivePanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel4.setText("Ημερομηνίας Γέννησης  ");
        adaptivePanel17.add(adaptiveLabel4);

        profileDataPanel.add(adaptivePanel17);

        adaptivePanel4.setLayout(new javax.swing.BoxLayout(adaptivePanel4, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ΗΗ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        adaptiveComboBox3.setFont(new java.awt.Font("Tahoma", 0, 8));
        adaptiveComboBox3.setMaximumSize(new java.awt.Dimension(60, 40));
        adaptiveComboBox3.setMinimumSize(new java.awt.Dimension(60, 40));
        adaptiveComboBox3.setPreferredSize(new java.awt.Dimension(60, 40));
        adaptivePanel4.add(adaptiveComboBox3);

        adaptiveComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ΜΜ", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", " " }));
        adaptiveComboBox4.setFont(new java.awt.Font("Tahoma", 0, 8));
        adaptiveComboBox4.setMaximumSize(new java.awt.Dimension(60, 40));
        adaptiveComboBox4.setMinimumSize(new java.awt.Dimension(60, 40));
        adaptiveComboBox4.setPreferredSize(new java.awt.Dimension(60, 40));
        adaptivePanel4.add(adaptiveComboBox4);

        adaptiveComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ΧΧΧΧ", "1950", "1960", "1970", "1980", "1990", "2000" }));
        adaptiveComboBox5.setFont(new java.awt.Font("Tahoma", 0, 8));
        adaptiveComboBox5.setMaximumSize(new java.awt.Dimension(80, 40));
        adaptiveComboBox5.setMinimumSize(new java.awt.Dimension(80, 40));
        adaptiveComboBox5.setPreferredSize(new java.awt.Dimension(80, 40));
        adaptivePanel4.add(adaptiveComboBox5);

        profileDataPanel.add(adaptivePanel4);

        adaptivePanel21.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel6.setText("Φύλλο  ");
        adaptivePanel21.add(adaptiveLabel6);

        profileDataPanel.add(adaptivePanel21);

        adaptivePanel5.setLayout(new javax.swing.BoxLayout(adaptivePanel5, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Επιλέξτε", "Άνδρας", "Γυναίκα" }));
        adaptiveComboBox9.setMaximumSize(new java.awt.Dimension(200, 40));
        adaptiveComboBox9.setMinimumSize(new java.awt.Dimension(200, 40));
        adaptiveComboBox9.setPreferredSize(new java.awt.Dimension(200, 40));
        adaptivePanel5.add(adaptiveComboBox9);

        profileDataPanel.add(adaptivePanel5);

        adaptivePanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel8.setText("Χώρα ");
        adaptivePanel22.add(adaptiveLabel8);

        profileDataPanel.add(adaptivePanel22);

        adaptivePanel6.setLayout(new javax.swing.BoxLayout(adaptivePanel6, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Χώρα", "Ελλάδα", "Γαλλία", "Γερμανία", "Ηνωμένο Βασίλειο", "Ιταλία", "Ισπανία" }));
        adaptiveComboBox6.setMaximumSize(new java.awt.Dimension(200, 40));
        adaptiveComboBox6.setMinimumSize(new java.awt.Dimension(200, 40));
        adaptiveComboBox6.setPreferredSize(new java.awt.Dimension(200, 40));
        adaptivePanel6.add(adaptiveComboBox6);

        profileDataPanel.add(adaptivePanel6);

        adaptivePanel23.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel9.setText("Πόλη ");
        adaptivePanel23.add(adaptiveLabel9);

        profileDataPanel.add(adaptivePanel23);

        adaptivePanel7.setLayout(new javax.swing.BoxLayout(adaptivePanel7, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveTextField7.setMaximumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField7.setMinimumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField7.setPreferredSize(new java.awt.Dimension(200, 40));
        adaptivePanel7.add(adaptiveTextField7);

        profileDataPanel.add(adaptivePanel7);

        adaptivePanel24.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel10.setText("Γλώσσα");
        adaptivePanel24.add(adaptiveLabel10);

        profileDataPanel.add(adaptivePanel24);

        adaptivePanel8.setLayout(new javax.swing.BoxLayout(adaptivePanel8, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Επιλέξτε", "Ελληνικά", "Αγγλικά", "Γαλλικά", "Γερμανικά", "Ισπανικά", "Ιταλικά", " " }));
        adaptiveComboBox7.setMaximumSize(new java.awt.Dimension(200, 40));
        adaptiveComboBox7.setMinimumSize(new java.awt.Dimension(200, 40));
        adaptiveComboBox7.setPreferredSize(new java.awt.Dimension(200, 40));
        adaptivePanel8.add(adaptiveComboBox7);

        profileDataPanel.add(adaptivePanel8);

        adaptivePanel25.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel11.setText("Τηλέφωνο");
        adaptivePanel25.add(adaptiveLabel11);

        profileDataPanel.add(adaptivePanel25);

        adaptivePanel9.setLayout(new javax.swing.BoxLayout(adaptivePanel9, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveTextField9.setMaximumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField9.setMinimumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField9.setPreferredSize(new java.awt.Dimension(200, 40));
        adaptivePanel9.add(adaptiveTextField9);

        profileDataPanel.add(adaptivePanel9);

        adaptivePanel13.setLayout(new javax.swing.BoxLayout(adaptivePanel13, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveLabel19.setText("Είδος Αναπηρίας (εαν υπάρχει)");
        adaptivePanel13.add(adaptiveLabel19);

        profileDataPanel.add(adaptivePanel13);

        adaptivePanel27.setLayout(new javax.swing.BoxLayout(adaptivePanel27, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Δεν υπάρχει", "Προβλήματα όρασης", "Αχρωματοψία", "Αστάθια άνω άκρων" }));
        adaptiveComboBox8.setMaximumSize(new java.awt.Dimension(200, 40));
        adaptiveComboBox8.setMinimumSize(new java.awt.Dimension(200, 40));
        adaptiveComboBox8.setPreferredSize(new java.awt.Dimension(200, 40));
        adaptivePanel27.add(adaptiveComboBox8);

        profileDataPanel.add(adaptivePanel27);

        adaptivePanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel12.setText("Όνομα Χρήστη");
        adaptivePanel26.add(adaptiveLabel12);

        profileDataPanel.add(adaptivePanel26);

        adaptivePanel10.setLayout(new javax.swing.BoxLayout(adaptivePanel10, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveTextField13.setMaximumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField13.setMinimumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField13.setPreferredSize(new java.awt.Dimension(200, 40));
        adaptivePanel10.add(adaptiveTextField13);

        profileDataPanel.add(adaptivePanel10);

        adaptivePanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel16.setText("Κωδικός");
        adaptivePanel20.add(adaptiveLabel16);

        profileDataPanel.add(adaptivePanel20);

        adaptivePanel11.setLayout(new javax.swing.BoxLayout(adaptivePanel11, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveTextField11.setMaximumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField11.setMinimumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField11.setPreferredSize(new java.awt.Dimension(200, 40));
        adaptivePanel11.add(adaptiveTextField11);

        profileDataPanel.add(adaptivePanel11);

        adaptivePanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel17.setText("Επαλήθευση Κωδικού ");
        adaptivePanel19.add(adaptiveLabel17);

        profileDataPanel.add(adaptivePanel19);

        adaptivePanel12.setLayout(new javax.swing.BoxLayout(adaptivePanel12, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveTextField12.setMaximumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField12.setMinimumSize(new java.awt.Dimension(200, 40));
        adaptiveTextField12.setPreferredSize(new java.awt.Dimension(200, 40));
        adaptivePanel12.add(adaptiveTextField12);

        profileDataPanel.add(adaptivePanel12);

        adaptivePanel28.setFunction("captchaImg");
        adaptivePanel28.setName("Panel.Content.Captcha"); // NOI18N
        adaptivePanel28.setLayout(new java.awt.BorderLayout());

        adaptivePanel34.setFunction("captchaImg");
        adaptivePanel34.setName("Panel.Content.Captcha"); // NOI18N

        javax.swing.GroupLayout adaptivePanel34Layout = new javax.swing.GroupLayout(adaptivePanel34);
        adaptivePanel34.setLayout(adaptivePanel34Layout);
        adaptivePanel34Layout.setHorizontalGroup(
            adaptivePanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );
        adaptivePanel34Layout.setVerticalGroup(
            adaptivePanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        adaptivePanel28.add(adaptivePanel34, java.awt.BorderLayout.CENTER);

        adaptivePanel35.setPreferredSize(new java.awt.Dimension(50, 1));

        javax.swing.GroupLayout adaptivePanel35Layout = new javax.swing.GroupLayout(adaptivePanel35);
        adaptivePanel35.setLayout(adaptivePanel35Layout);
        adaptivePanel35Layout.setHorizontalGroup(
            adaptivePanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        adaptivePanel35Layout.setVerticalGroup(
            adaptivePanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        adaptivePanel28.add(adaptivePanel35, java.awt.BorderLayout.EAST);

        profileDataPanel.add(adaptivePanel28);

        adaptivePanel18.setName(""); // NOI18N
        adaptivePanel18.setLayout(new java.awt.GridLayout(1, 4, 20, 0));

        refreshButton.setFunction("");
        adaptivePanel18.add(refreshButton);
        adaptivePanel18.add(listenButton);
        adaptivePanel18.add(helpButton);

        profileDataPanel.add(adaptivePanel18);

        adaptivePanel29.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel14.setFont(new java.awt.Font("Tahoma", 2, 11));
        adaptiveLabel14.setText("Εισάγετε εδώ το παραπάνω κείμενο");
        adaptivePanel29.add(adaptiveLabel14);

        profileDataPanel.add(adaptivePanel29);

        adaptivePanel30.setLayout(new javax.swing.BoxLayout(adaptivePanel30, javax.swing.BoxLayout.LINE_AXIS));
        adaptivePanel30.add(adaptiveTextField4);

        profileDataPanel.add(adaptivePanel30);

        contentPanel.add(profileDataPanel, java.awt.BorderLayout.CENTER);

        buttonData.setLayout(new javax.swing.BoxLayout(buttonData, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout adaptivePanel31Layout = new javax.swing.GroupLayout(adaptivePanel31);
        adaptivePanel31.setLayout(adaptivePanel31Layout);
        adaptivePanel31Layout.setHorizontalGroup(
            adaptivePanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        adaptivePanel31Layout.setVerticalGroup(
            adaptivePanel31Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        buttonData.add(adaptivePanel31);

        acceptanceButton.setText("Δημιουργία Λογαριασμού");
        acceptanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptanceButtonActionPerformed(evt);
            }
        });
        buttonData.add(acceptanceButton);

        adaptivePanel33.setMaximumSize(new java.awt.Dimension(30, 30));
        adaptivePanel33.setMinimumSize(new java.awt.Dimension(30, 30));
        adaptivePanel33.setPreferredSize(new java.awt.Dimension(30, 30));

        javax.swing.GroupLayout adaptivePanel33Layout = new javax.swing.GroupLayout(adaptivePanel33);
        adaptivePanel33.setLayout(adaptivePanel33Layout);
        adaptivePanel33Layout.setHorizontalGroup(
            adaptivePanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        adaptivePanel33Layout.setVerticalGroup(
            adaptivePanel33Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        buttonData.add(adaptivePanel33);

        cancelButton.setText("Ακύρωση");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonData.add(cancelButton);

        javax.swing.GroupLayout adaptivePanel32Layout = new javax.swing.GroupLayout(adaptivePanel32);
        adaptivePanel32.setLayout(adaptivePanel32Layout);
        adaptivePanel32Layout.setHorizontalGroup(
            adaptivePanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 306, Short.MAX_VALUE)
        );
        adaptivePanel32Layout.setVerticalGroup(
            adaptivePanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        buttonData.add(adaptivePanel32);

        contentPanel.add(buttonData, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout eastPanelLayout = new javax.swing.GroupLayout(eastPanel);
        eastPanel.setLayout(eastPanelLayout);
        eastPanelLayout.setHorizontalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );
        eastPanelLayout.setVerticalGroup(
            eastPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
        );

        contentPanel.add(eastPanel, java.awt.BorderLayout.EAST);

        javax.swing.GroupLayout westPanelLayout = new javax.swing.GroupLayout(westPanel);
        westPanel.setLayout(westPanelLayout);
        westPanelLayout.setHorizontalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );
        westPanelLayout.setVerticalGroup(
            westPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 822, Short.MAX_VALUE)
        );

        contentPanel.add(westPanel, java.awt.BorderLayout.WEST);

        adaptiveLabel13.setFont(new java.awt.Font("Tahoma", 1, 14));
        adaptiveLabel13.setText("Δημιουργία Λογαριασμού");
        topPanel.add(adaptiveLabel13);

        contentPanel.add(topPanel, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(contentPanel);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

private void acceptanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptanceButtonActionPerformed
        MainWindowPC.showPanel(new Login1());
}//GEN-LAST:event_acceptanceButtonActionPerformed

private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
       MainWindowPC.showPanel(new Login1());
}//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.AdaptiveButton acceptanceButton;
    private widgets.combobox.AdaptiveComboBox adaptiveComboBox1;
    private widgets.combobox.AdaptiveComboBox adaptiveComboBox2;
    private widgets.combobox.AdaptiveComboBox adaptiveComboBox3;
    private widgets.combobox.AdaptiveComboBox adaptiveComboBox4;
    private widgets.combobox.AdaptiveComboBox adaptiveComboBox5;
    private widgets.combobox.AdaptiveComboBox adaptiveComboBox6;
    private widgets.combobox.AdaptiveComboBox adaptiveComboBox7;
    private widgets.combobox.AdaptiveComboBox adaptiveComboBox8;
    private widgets.combobox.AdaptiveComboBox adaptiveComboBox9;
    private widgets.label.AdaptiveLabel adaptiveLabel1;
    private widgets.label.AdaptiveLabel adaptiveLabel10;
    private widgets.label.AdaptiveLabel adaptiveLabel11;
    private widgets.label.AdaptiveLabel adaptiveLabel12;
    private widgets.label.AdaptiveLabel adaptiveLabel13;
    private widgets.label.AdaptiveLabel adaptiveLabel14;
    private widgets.label.AdaptiveLabel adaptiveLabel16;
    private widgets.label.AdaptiveLabel adaptiveLabel17;
    private widgets.label.AdaptiveLabel adaptiveLabel19;
    private widgets.label.AdaptiveLabel adaptiveLabel2;
    private widgets.label.AdaptiveLabel adaptiveLabel3;
    private widgets.label.AdaptiveLabel adaptiveLabel4;
    private widgets.label.AdaptiveLabel adaptiveLabel5;
    private widgets.label.AdaptiveLabel adaptiveLabel6;
    private widgets.label.AdaptiveLabel adaptiveLabel7;
    private widgets.label.AdaptiveLabel adaptiveLabel8;
    private widgets.label.AdaptiveLabel adaptiveLabel9;
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel10;
    private widgets.panel.AdaptivePanel adaptivePanel11;
    private widgets.panel.AdaptivePanel adaptivePanel12;
    private widgets.panel.AdaptivePanel adaptivePanel13;
    private widgets.panel.AdaptivePanel adaptivePanel14;
    private widgets.panel.AdaptivePanel adaptivePanel15;
    private widgets.panel.AdaptivePanel adaptivePanel16;
    private widgets.panel.AdaptivePanel adaptivePanel17;
    private widgets.panel.AdaptivePanel adaptivePanel18;
    private widgets.panel.AdaptivePanel adaptivePanel19;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.panel.AdaptivePanel adaptivePanel20;
    private widgets.panel.AdaptivePanel adaptivePanel21;
    private widgets.panel.AdaptivePanel adaptivePanel22;
    private widgets.panel.AdaptivePanel adaptivePanel23;
    private widgets.panel.AdaptivePanel adaptivePanel24;
    private widgets.panel.AdaptivePanel adaptivePanel25;
    private widgets.panel.AdaptivePanel adaptivePanel26;
    private widgets.panel.AdaptivePanel adaptivePanel27;
    private widgets.panel.AdaptivePanel adaptivePanel28;
    private widgets.panel.AdaptivePanel adaptivePanel29;
    private widgets.panel.AdaptivePanel adaptivePanel3;
    private widgets.panel.AdaptivePanel adaptivePanel30;
    private widgets.panel.AdaptivePanel adaptivePanel31;
    private widgets.panel.AdaptivePanel adaptivePanel32;
    private widgets.panel.AdaptivePanel adaptivePanel33;
    private widgets.panel.AdaptivePanel adaptivePanel34;
    private widgets.panel.AdaptivePanel adaptivePanel35;
    private widgets.panel.AdaptivePanel adaptivePanel4;
    private widgets.panel.AdaptivePanel adaptivePanel5;
    private widgets.panel.AdaptivePanel adaptivePanel6;
    private widgets.panel.AdaptivePanel adaptivePanel7;
    private widgets.panel.AdaptivePanel adaptivePanel8;
    private widgets.panel.AdaptivePanel adaptivePanel9;
    private widgets.textfield.AdaptiveTextField adaptiveTextField1;
    private widgets.textfield.AdaptiveTextField adaptiveTextField11;
    private widgets.textfield.AdaptiveTextField adaptiveTextField12;
    private widgets.textfield.AdaptiveTextField adaptiveTextField13;
    private widgets.textfield.AdaptiveTextField adaptiveTextField2;
    private widgets.textfield.AdaptiveTextField adaptiveTextField3;
    private widgets.textfield.AdaptiveTextField adaptiveTextField4;
    private widgets.textfield.AdaptiveTextField adaptiveTextField7;
    private widgets.textfield.AdaptiveTextField adaptiveTextField9;
    private widgets.panel.AdaptivePanel buttonData;
    private widgets.button.AdaptiveButton cancelButton;
    private widgets.panel.AdaptivePanel contentPanel;
    private widgets.panel.AdaptivePanel eastPanel;
    private widgets.button.AdaptiveButton helpButton;
    private javax.swing.JScrollPane jScrollPane1;
    private widgets.button.AdaptiveButton listenButton;
    private widgets.panel.AdaptivePanel profileDataPanel;
    private widgets.button.AdaptiveButton refreshButton;
    private widgets.panel.AdaptivePanel topPanel;
    private widgets.panel.AdaptivePanel westPanel;
    // End of variables declaration//GEN-END:variables
}
