/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddContactSuccess.java
 *
 * Created on Dec 2, 2011, 15:00:29 PM
 */
package assignment2.pda;

import pda.MainWindowPDA;
import utilities.Adaptation;

/**
 *
 * @author koutsop
 */
public class AddContactSuccess extends javax.swing.JPanel {
    /** Creates new form AddContactSuccess */
    public AddContactSuccess() {
        initComponents();
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);		
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new widgets.panel.AdaptivePanel();
        adaptivePanel3 = new widgets.panel.AdaptivePanel();
        adaptiveLabel1 = new widgets.label.AdaptiveLabel();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        adaptivePanel5 = new widgets.panel.AdaptivePanel();
        adaptivePanel4 = new widgets.panel.AdaptivePanel();
        adaptivePanel6 = new widgets.panel.AdaptivePanel();
        adaptiveLabel2 = new widgets.label.AdaptiveLabel();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        adaptivePanel7 = new widgets.panel.AdaptivePanel();
        adaptiveButton1 = new widgets.button.AdaptiveButton();
        adaptiveButton2 = new widgets.button.AdaptiveButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        contentPanel.setPreferredSize(new java.awt.Dimension(400, 200));
        contentPanel.setLayout(new java.awt.BorderLayout(1, 20));

        adaptiveLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        adaptiveLabel1.setText("Το μήνυμά σας εστάλη επιτυχώς στο χρήστη: ");

        javax.swing.GroupLayout adaptivePanel3Layout = new javax.swing.GroupLayout(adaptivePanel3);
        adaptivePanel3.setLayout(adaptivePanel3Layout);
        adaptivePanel3Layout.setHorizontalGroup(
            adaptivePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
            .addGroup(adaptivePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(adaptivePanel3Layout.createSequentialGroup()
                    .addGap(0, 282, Short.MAX_VALUE)
                    .addComponent(adaptiveLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 283, Short.MAX_VALUE)))
        );
        adaptivePanel3Layout.setVerticalGroup(
            adaptivePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 17, Short.MAX_VALUE)
            .addGroup(adaptivePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(adaptivePanel3Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(adaptiveLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        contentPanel.add(adaptivePanel3, java.awt.BorderLayout.NORTH);

        adaptivePanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        adaptivePanel5.setLayout(new javax.swing.BoxLayout(adaptivePanel5, javax.swing.BoxLayout.PAGE_AXIS));

        adaptivePanel4.setFunction("marigiannaImg");
        adaptivePanel4.setMaximumSize(new java.awt.Dimension(150, 150));
        adaptivePanel4.setMinimumSize(new java.awt.Dimension(150, 150));
        adaptivePanel4.setName("Panel.Content.MarigiannaImage"); // NOI18N
        adaptivePanel4.setPreferredSize(new java.awt.Dimension(150, 150));

        javax.swing.GroupLayout adaptivePanel4Layout = new javax.swing.GroupLayout(adaptivePanel4);
        adaptivePanel4.setLayout(adaptivePanel4Layout);
        adaptivePanel4Layout.setHorizontalGroup(
            adaptivePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        adaptivePanel4Layout.setVerticalGroup(
            adaptivePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        adaptivePanel5.add(adaptivePanel4);

        adaptivePanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 15));

        adaptiveLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adaptiveLabel2.setText("Μαριγίαννα Σκουραδάκη");
        adaptivePanel6.add(adaptiveLabel2);

        adaptivePanel5.add(adaptivePanel6);

        adaptivePanel2.add(adaptivePanel5);

        contentPanel.add(adaptivePanel2, java.awt.BorderLayout.CENTER);

        adaptivePanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 20));

        adaptivePanel7.setLayout(new java.awt.GridLayout(1, 2, 25, 0));

        adaptiveButton1.setText("Νέα Αναζήτηση ");
        adaptiveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton1ActionPerformed(evt);
            }
        });
        adaptivePanel7.add(adaptiveButton1);

        adaptiveButton2.setText("Ακύρωση");
        adaptiveButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton2ActionPerformed(evt);
            }
        });
        adaptivePanel7.add(adaptiveButton2);

        adaptivePanel1.add(adaptivePanel7);

        contentPanel.add(adaptivePanel1, java.awt.BorderLayout.PAGE_END);

        add(contentPanel);
    }// </editor-fold>//GEN-END:initComponents

	private void adaptiveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton1ActionPerformed
		MainWindowPDA.showPanel(new SearchForNewContact());
	}//GEN-LAST:event_adaptiveButton1ActionPerformed

	private void adaptiveButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton2ActionPerformed
		MainWindowPDA.showPanel(new PDAMainView());
	}//GEN-LAST:event_adaptiveButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.AdaptiveButton adaptiveButton1;
    private widgets.button.AdaptiveButton adaptiveButton2;
    private widgets.label.AdaptiveLabel adaptiveLabel1;
    private widgets.label.AdaptiveLabel adaptiveLabel2;
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.panel.AdaptivePanel adaptivePanel3;
    private widgets.panel.AdaptivePanel adaptivePanel4;
    private widgets.panel.AdaptivePanel adaptivePanel5;
    private widgets.panel.AdaptivePanel adaptivePanel6;
    private widgets.panel.AdaptivePanel adaptivePanel7;
    private widgets.panel.AdaptivePanel contentPanel;
    // End of variables declaration//GEN-END:variables
}
