/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Call.java
 *
 * Created on 2 Δεκ 2011, 11:41:06 μμ
 */
package assignment2.pda;

import javax.swing.ImageIcon;
import pda.MainWindowPDA;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class Call extends javax.swing.JPanel {

	/** Creates new form Call */
	public Call() {
		initComponents();
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
		
		String path = DMSLConnector.getInstance().getClient(false).Evaluate("MuteVideoPDAButton");
		muteButton.setIcon(new ImageIcon(getClass().getResource(path)));		

		path = DMSLConnector.getInstance().getClient(false).Evaluate("CloseVideoPDAButton");
		closeButton.setIcon(new ImageIcon(getClass().getResource(path)));	

		path = DMSLConnector.getInstance().getClient(false).Evaluate("EndCallPDAButton");
		endCallButton.setIcon(new ImageIcon(getClass().getResource(path)));	
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adaptivePanel4 = new widgets.panel.AdaptivePanel();
        adaptivePanel5 = new widgets.panel.AdaptivePanel();
        muteButton = new widgets.button.AdaptiveButton();
        adaptivePanel7 = new widgets.panel.AdaptivePanel();
        closeButton = new widgets.button.AdaptiveButton();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        marigiannaPanel = new widgets.panel.AdaptivePanel();
        adaptivePanel8 = new widgets.panel.AdaptivePanel();
        adaptivePanel3 = new widgets.panel.AdaptivePanel();
        endCallButton = new widgets.button.AdaptiveButton();

        setLayout(new java.awt.BorderLayout(0, 15));

        adaptivePanel4.setFunction("TransparentPanel");
        adaptivePanel4.setName("Panel.TransparentPanel"); // NOI18N
        adaptivePanel4.setLayout(new java.awt.BorderLayout());

        adaptivePanel5.setFunction("TransparentPanel");
        adaptivePanel5.setName("Panel.TransparentPanel"); // NOI18N
        adaptivePanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        muteButton.setFunction("EmptyButton");
        muteButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptivePanel5.add(muteButton);

        adaptivePanel4.add(adaptivePanel5, java.awt.BorderLayout.WEST);

        adaptivePanel7.setFunction("TransparentPanel");
        adaptivePanel7.setName("Panel.TransparentPanel"); // NOI18N
        adaptivePanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        closeButton.setFunction("EmptyButton");
        closeButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        adaptivePanel7.add(closeButton);

        adaptivePanel4.add(adaptivePanel7, java.awt.BorderLayout.EAST);

        add(adaptivePanel4, java.awt.BorderLayout.NORTH);

        adaptivePanel2.setFunction("TransparentPanel");
        adaptivePanel2.setName("Panel.TransparentPanel"); // NOI18N
        adaptivePanel2.setLayout(new java.awt.BorderLayout(60, 0));
        adaptivePanel2.add(adaptivePanel1, java.awt.BorderLayout.EAST);

        marigiannaPanel.setFunction("marigiannaImg");
        marigiannaPanel.setName("Panel.Content.MarigiannaImage"); // NOI18N

        javax.swing.GroupLayout marigiannaPanelLayout = new javax.swing.GroupLayout(marigiannaPanel);
        marigiannaPanel.setLayout(marigiannaPanelLayout);
        marigiannaPanelLayout.setHorizontalGroup(
            marigiannaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 415, Short.MAX_VALUE)
        );
        marigiannaPanelLayout.setVerticalGroup(
            marigiannaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 186, Short.MAX_VALUE)
        );

        adaptivePanel2.add(marigiannaPanel, java.awt.BorderLayout.CENTER);
        adaptivePanel2.add(adaptivePanel8, java.awt.BorderLayout.WEST);

        add(adaptivePanel2, java.awt.BorderLayout.CENTER);

        adaptivePanel3.setFunction("TransparentPanel");
        adaptivePanel3.setName("Panel.TransparentPanel"); // NOI18N
        adaptivePanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 10));

        endCallButton.setFunction("EmptyButton");
        endCallButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        endCallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endCallButtonActionPerformed(evt);
            }
        });
        adaptivePanel3.add(endCallButton);

        add(adaptivePanel3, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

	private void endCallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endCallButtonActionPerformed
		MainWindowPDA.showPanel(new Chat());
	}//GEN-LAST:event_endCallButtonActionPerformed

	private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
		MainWindowPDA.showPanel(new PDAMainView());
	}//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.panel.AdaptivePanel adaptivePanel3;
    private widgets.panel.AdaptivePanel adaptivePanel4;
    private widgets.panel.AdaptivePanel adaptivePanel5;
    private widgets.panel.AdaptivePanel adaptivePanel7;
    private widgets.panel.AdaptivePanel adaptivePanel8;
    private widgets.button.AdaptiveButton closeButton;
    private widgets.button.AdaptiveButton endCallButton;
    private widgets.panel.AdaptivePanel marigiannaPanel;
    private widgets.button.AdaptiveButton muteButton;
    // End of variables declaration//GEN-END:variables
}
