/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GeneralSettingsPanel.java
 *
 * Created on 2 Δεκ 2011, 1:16:41 μμ
 */
package assignment2.pda;

/**
 *
 * @author koutsop
 */
public class GeneralSettingsPanel extends javax.swing.JPanel {

	/** Creates new form GeneralSettingsPanel */
	public GeneralSettingsPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        adaptiveLabel1 = new widgets.label.AdaptiveLabel();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        adaptiveCheckBox1 = new widgets.checkbox.AdaptiveCheckBox();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        adaptivePanel1.setLayout(new java.awt.BorderLayout(0, 20));

        adaptiveLabel1.setText("Chat");
        adaptivePanel1.add(adaptiveLabel1, java.awt.BorderLayout.PAGE_START);

        adaptivePanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        adaptiveCheckBox1.setText("Start automaticly");
        adaptivePanel2.add(adaptiveCheckBox1);

        adaptivePanel1.add(adaptivePanel2, java.awt.BorderLayout.CENTER);

        add(adaptivePanel1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.checkbox.AdaptiveCheckBox adaptiveCheckBox1;
    private widgets.label.AdaptiveLabel adaptiveLabel1;
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    // End of variables declaration//GEN-END:variables
}
