/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Help.java
 *
 * Created on 1 Δεκ 2011, 9:00:38 μμ
 */
package assignment2.pda;

import pda.MainWindowPDA;

/**
 *
 * @author koutsop
 */
public class Help extends javax.swing.JPanel {

	/** Creates new form Help */
	public Help() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messagePanel = new widgets.panel.AdaptivePanel();
        adaptiveLabel2 = new widgets.label.AdaptiveLabel();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        adaptiveLabel1 = new widgets.label.AdaptiveLabel();
        adaptiveTextField1 = new widgets.textfield.AdaptiveTextField();
        buttonsPabel = new widgets.panel.AdaptivePanel();
        searchButton = new widgets.button.AdaptiveButton();
        cancelButton = new widgets.button.AdaptiveButton();

        setLayout(new java.awt.BorderLayout());

        messagePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 50));

        adaptiveLabel2.setText("Plitrologiste ena keyword gia gia bhh8eia?");
        messagePanel.add(adaptiveLabel2);

        add(messagePanel, java.awt.BorderLayout.NORTH);

        adaptiveLabel1.setText("e-mail:");
        adaptivePanel1.add(adaptiveLabel1);

        adaptiveTextField1.setText("adaptiveTextField1");
        adaptivePanel1.add(adaptiveTextField1);

        add(adaptivePanel1, java.awt.BorderLayout.CENTER);

        buttonsPabel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 50));

        searchButton.setText("Αναζήτηση");
        buttonsPabel.add(searchButton);

        cancelButton.setText("Ακήρωση");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonsPabel.add(cancelButton);

        add(buttonsPabel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		MainWindowPDA.showPanel(new PDAMainView());
	}//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.label.AdaptiveLabel adaptiveLabel1;
    private widgets.label.AdaptiveLabel adaptiveLabel2;
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.textfield.AdaptiveTextField adaptiveTextField1;
    private widgets.panel.AdaptivePanel buttonsPabel;
    private widgets.button.AdaptiveButton cancelButton;
    private widgets.panel.AdaptivePanel messagePanel;
    private widgets.button.AdaptiveButton searchButton;
    // End of variables declaration//GEN-END:variables
}
