/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NotificationsSettingsPanel.java
 *
 * Created on 1 Δεκ 2011, 11:45:20 μμ
 */
package assignment2.pda;

/**
 *
 * @author koutsop
 */
public class NotificationsSettingsPanel extends javax.swing.JPanel {

	/** Creates new form NotificationsSettingsPanel */
	public NotificationsSettingsPanel() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        adaptiveLabel1 = new widgets.label.AdaptiveLabel();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        adaptivePanel3 = new widgets.panel.AdaptivePanel();
        adaptivePanel6 = new widgets.panel.AdaptivePanel();
        adaptiveLabel2 = new widgets.label.AdaptiveLabel();
        adaptivePanel7 = new widgets.panel.AdaptivePanel();
        adaptiveCheckBox1 = new widgets.checkbox.AdaptiveCheckBox();
        adaptivePanel4 = new widgets.panel.AdaptivePanel();
        adaptivePanel8 = new widgets.panel.AdaptivePanel();
        adaptiveLabel3 = new widgets.label.AdaptiveLabel();
        adaptivePanel9 = new widgets.panel.AdaptivePanel();
        adaptiveCheckBox2 = new widgets.checkbox.AdaptiveCheckBox();
        adaptivePanel5 = new widgets.panel.AdaptivePanel();
        adaptivePanel10 = new widgets.panel.AdaptivePanel();
        adaptiveLabel4 = new widgets.label.AdaptiveLabel();
        adaptivePanel11 = new widgets.panel.AdaptivePanel();
        adaptiveCheckBox3 = new widgets.checkbox.AdaptiveCheckBox();
        adaptivePanel12 = new widgets.panel.AdaptivePanel();
        adaptiveCheckBox4 = new widgets.checkbox.AdaptiveCheckBox();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        adaptivePanel1.setLayout(new java.awt.BorderLayout(0, 10));

        adaptiveLabel1.setText("Notifications");
        adaptivePanel1.add(adaptiveLabel1, java.awt.BorderLayout.NORTH);

        adaptivePanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        adaptivePanel2.setLayout(new java.awt.GridLayout(3, 1, 0, 15));

        adaptivePanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        adaptivePanel3.setLayout(new java.awt.GridLayout(2, 1));

        adaptivePanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        adaptiveLabel2.setText("Incoming Chat");
        adaptivePanel6.add(adaptiveLabel2);

        adaptivePanel3.add(adaptivePanel6);

        adaptivePanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        adaptiveCheckBox1.setText("Show Notification");
        adaptivePanel7.add(adaptiveCheckBox1);

        adaptivePanel3.add(adaptivePanel7);

        adaptivePanel2.add(adaptivePanel3);

        adaptivePanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        adaptivePanel4.setLayout(new java.awt.GridLayout(2, 1));

        adaptivePanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        adaptiveLabel3.setText("Incoming Call");
        adaptivePanel8.add(adaptiveLabel3);

        adaptivePanel4.add(adaptivePanel8);

        adaptivePanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        adaptiveCheckBox2.setText("Show Notification");
        adaptivePanel9.add(adaptiveCheckBox2);

        adaptivePanel4.add(adaptivePanel9);

        adaptivePanel2.add(adaptivePanel4);

        adaptivePanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        adaptivePanel5.setLayout(new java.awt.GridLayout(2, 1));

        adaptivePanel10.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        adaptiveLabel4.setText("Incoming Video Call");
        adaptivePanel10.add(adaptiveLabel4);

        adaptivePanel5.add(adaptivePanel10);

        adaptivePanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));

        adaptiveCheckBox3.setText("Show Notification");
        adaptivePanel11.add(adaptiveCheckBox3);

        adaptivePanel5.add(adaptivePanel11);

        adaptivePanel2.add(adaptivePanel5);

        adaptivePanel1.add(adaptivePanel2, java.awt.BorderLayout.CENTER);

        adaptivePanel12.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        adaptivePanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        adaptiveCheckBox4.setText("Disaboke all notifications");
        adaptivePanel12.add(adaptiveCheckBox4);

        adaptivePanel1.add(adaptivePanel12, java.awt.BorderLayout.SOUTH);

        add(adaptivePanel1);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.checkbox.AdaptiveCheckBox adaptiveCheckBox1;
    private widgets.checkbox.AdaptiveCheckBox adaptiveCheckBox2;
    private widgets.checkbox.AdaptiveCheckBox adaptiveCheckBox3;
    private widgets.checkbox.AdaptiveCheckBox adaptiveCheckBox4;
    private widgets.label.AdaptiveLabel adaptiveLabel1;
    private widgets.label.AdaptiveLabel adaptiveLabel2;
    private widgets.label.AdaptiveLabel adaptiveLabel3;
    private widgets.label.AdaptiveLabel adaptiveLabel4;
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel10;
    private widgets.panel.AdaptivePanel adaptivePanel11;
    private widgets.panel.AdaptivePanel adaptivePanel12;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.panel.AdaptivePanel adaptivePanel3;
    private widgets.panel.AdaptivePanel adaptivePanel4;
    private widgets.panel.AdaptivePanel adaptivePanel5;
    private widgets.panel.AdaptivePanel adaptivePanel6;
    private widgets.panel.AdaptivePanel adaptivePanel7;
    private widgets.panel.AdaptivePanel adaptivePanel8;
    private widgets.panel.AdaptivePanel adaptivePanel9;
    // End of variables declaration//GEN-END:variables
}
