/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Profile.java
 *
 * Created on 1 Δεκ 2011, 6:21:45 μμ
 */
package assignment2.pda;

import javax.swing.ImageIcon;
import pda.MainWindowPDA;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class Profile extends javax.swing.JPanel {

	/** Creates new form Profile */
	public Profile() {
		initComponents();
        
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
        
        String path = DMSLConnector.getInstance().getClient(false).Evaluate("OnlineButton");
        onlineButton.setIcon(new ImageIcon(getClass().getResource(path)));  
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("AwayButton");
        awayButton.setIcon(new ImageIcon(getClass().getResource(path)));  
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("BusyButton");
        busyButton.setIcon(new ImageIcon(getClass().getResource(path))); 
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("OfflineButton");
        offlineButton.setIcon(new ImageIcon(getClass().getResource(path))); 
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("CancelButton");
        cancelButton.setIcon(new ImageIcon(getClass().getResource(path)));

        path = DMSLConnector.getInstance().getClient(false).Evaluate("AcceptanceButton");
        acceptanceButton.setIcon(new ImageIcon(getClass().getResource(path)));		
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        contentPanel = new widgets.panel.AdaptivePanel();
        profileImagePanel = new widgets.panel.AdaptivePanel();
        adaptivePanel29 = new widgets.panel.AdaptivePanel();
        adaptivePanel30 = new widgets.panel.AdaptivePanel();
        adaptivePanel31 = new widgets.panel.AdaptivePanel();
        adaptiveButton3 = new widgets.button.AdaptiveButton();
        adaptivePanel32 = new widgets.panel.AdaptivePanel();
        onlineButton = new widgets.button.AdaptiveButton();
        awayButton = new widgets.button.AdaptiveButton();
        busyButton = new widgets.button.AdaptiveButton();
        offlineButton = new widgets.button.AdaptiveButton();
        adaptivePanel37 = new widgets.panel.AdaptivePanel();
        profileDataPanel = new widgets.panel.AdaptivePanel();
        adaptivePanel18 = new widgets.panel.AdaptivePanel();
        adaptiveLabel13 = new widgets.label.AdaptiveLabel();
        adaptivePanel13 = new widgets.panel.AdaptivePanel();
        adaptiveTextField13 = new widgets.textfield.AdaptiveTextField();
        adaptivePanel20 = new widgets.panel.AdaptivePanel();
        adaptiveLabel11 = new widgets.label.AdaptiveLabel();
        adaptivePanel11 = new widgets.panel.AdaptivePanel();
        adaptiveTextField11 = new widgets.textfield.AdaptiveTextField();
        adaptivePanel19 = new widgets.panel.AdaptivePanel();
        adaptiveLabel12 = new widgets.label.AdaptiveLabel();
        adaptivePanel12 = new widgets.panel.AdaptivePanel();
        adaptiveTextField12 = new widgets.textfield.AdaptiveTextField();
        buttonData = new widgets.panel.AdaptivePanel();
        acceptanceButton = new widgets.button.AdaptiveButton();
        cancelButton = new widgets.button.AdaptiveButton();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        contentPanel.setLayout(new java.awt.BorderLayout());

        profileImagePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 1, 0));
        profileImagePanel.setLayout(new java.awt.BorderLayout(8, 0));

        adaptivePanel29.setFunction("koutsopImg");
        adaptivePanel29.setMaximumSize(new java.awt.Dimension(100, 100));
        adaptivePanel29.setMinimumSize(new java.awt.Dimension(100, 100));
        adaptivePanel29.setName("Panel.Content.KoutsopImage"); // NOI18N
        adaptivePanel29.setPreferredSize(new java.awt.Dimension(100, 100));
        adaptivePanel29.setLayout(new javax.swing.BoxLayout(adaptivePanel29, javax.swing.BoxLayout.LINE_AXIS));
        profileImagePanel.add(adaptivePanel29, java.awt.BorderLayout.WEST);

        adaptivePanel30.setLayout(new javax.swing.BoxLayout(adaptivePanel30, javax.swing.BoxLayout.PAGE_AXIS));

        adaptivePanel31.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        adaptiveButton3.setText("Επιλογή Εικόνας");
        adaptivePanel31.add(adaptiveButton3);

        adaptivePanel30.add(adaptivePanel31);

        adaptivePanel32.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        onlineButton.setSelected(true);
        adaptivePanel32.add(onlineButton);
        adaptivePanel32.add(awayButton);
        adaptivePanel32.add(busyButton);
        adaptivePanel32.add(offlineButton);

        adaptivePanel30.add(adaptivePanel32);

        profileImagePanel.add(adaptivePanel30, java.awt.BorderLayout.CENTER);

        contentPanel.add(profileImagePanel, java.awt.BorderLayout.NORTH);

        adaptivePanel37.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 10));

        profileDataPanel.setLayout(new java.awt.GridLayout(3, 2, 0, 10));

        adaptivePanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel13.setText("Status");
        adaptivePanel18.add(adaptiveLabel13);

        profileDataPanel.add(adaptivePanel18);

        adaptivePanel13.setLayout(new javax.swing.BoxLayout(adaptivePanel13, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveTextField13.setText("ΗΥ-564 άσκηση 3");
        adaptivePanel13.add(adaptiveTextField13);

        profileDataPanel.add(adaptivePanel13);

        adaptivePanel20.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel11.setText("Κωδικός");
        adaptivePanel20.add(adaptiveLabel11);

        profileDataPanel.add(adaptivePanel20);

        adaptivePanel11.setLayout(new javax.swing.BoxLayout(adaptivePanel11, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveTextField11.setText("**********");
        adaptivePanel11.add(adaptiveTextField11);

        profileDataPanel.add(adaptivePanel11);

        adaptivePanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        adaptiveLabel12.setText("Επαλήθευση Κωδικού ");
        adaptivePanel19.add(adaptiveLabel12);

        profileDataPanel.add(adaptivePanel19);

        adaptivePanel12.setLayout(new javax.swing.BoxLayout(adaptivePanel12, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveTextField12.setText("**********");
        adaptivePanel12.add(adaptiveTextField12);

        profileDataPanel.add(adaptivePanel12);

        adaptivePanel37.add(profileDataPanel);

        contentPanel.add(adaptivePanel37, java.awt.BorderLayout.CENTER);

        buttonData.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 38, 50));

        acceptanceButton.setText("Αποθήκευση");
        acceptanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptanceButtonActionPerformed(evt);
            }
        });
        buttonData.add(acceptanceButton);

        cancelButton.setText("Ακύρωση");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        buttonData.add(cancelButton);

        contentPanel.add(buttonData, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setViewportView(contentPanel);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

	private void acceptanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptanceButtonActionPerformed
		MainWindowPDA.showPanel(new PDAMainView());
	}//GEN-LAST:event_acceptanceButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		MainWindowPDA.showPanel(new PDAMainView());
	}//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.AdaptiveButton acceptanceButton;
    private widgets.button.AdaptiveButton adaptiveButton3;
    private widgets.label.AdaptiveLabel adaptiveLabel11;
    private widgets.label.AdaptiveLabel adaptiveLabel12;
    private widgets.label.AdaptiveLabel adaptiveLabel13;
    private widgets.panel.AdaptivePanel adaptivePanel11;
    private widgets.panel.AdaptivePanel adaptivePanel12;
    private widgets.panel.AdaptivePanel adaptivePanel13;
    private widgets.panel.AdaptivePanel adaptivePanel18;
    private widgets.panel.AdaptivePanel adaptivePanel19;
    private widgets.panel.AdaptivePanel adaptivePanel20;
    private widgets.panel.AdaptivePanel adaptivePanel29;
    private widgets.panel.AdaptivePanel adaptivePanel30;
    private widgets.panel.AdaptivePanel adaptivePanel31;
    private widgets.panel.AdaptivePanel adaptivePanel32;
    private widgets.panel.AdaptivePanel adaptivePanel37;
    private widgets.textfield.AdaptiveTextField adaptiveTextField11;
    private widgets.textfield.AdaptiveTextField adaptiveTextField12;
    private widgets.textfield.AdaptiveTextField adaptiveTextField13;
    private widgets.button.AdaptiveButton awayButton;
    private widgets.button.AdaptiveButton busyButton;
    private widgets.panel.AdaptivePanel buttonData;
    private widgets.button.AdaptiveButton cancelButton;
    private widgets.panel.AdaptivePanel contentPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private widgets.button.AdaptiveButton offlineButton;
    private widgets.button.AdaptiveButton onlineButton;
    private widgets.panel.AdaptivePanel profileDataPanel;
    private widgets.panel.AdaptivePanel profileImagePanel;
    // End of variables declaration//GEN-END:variables
}
