/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SettingsMainView.java
 *
 * Created on 1 Δεκ 2011, 10:40:09 μμ
 */
package assignment2.pda;

import java.awt.event.MouseEvent;
import javax.sound.midi.SysexMessage;
import javax.swing.JPanel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import pda.MainWindowPDA;

/**
 *
 * @author koutsop
 */
public class SettingsMainView extends javax.swing.JPanel {

	/** Creates new form SettingsMainView */
	public SettingsMainView() {
		initComponents();
	}
	
	private void showPanel (JPanel p) {
		centerPanel.removeAll();
		p.setVisible(true);
		centerPanel.add(p);
		centerPanel.repaint();
		centerPanel.validate();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        westPanel = new widgets.panel.AdaptivePanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adaptiveList1 = new widgets.list.AdaptiveList();
        centerPanel = new widgets.panel.AdaptivePanel();
        south = new widgets.panel.AdaptivePanel();
        hellpPanel = new widgets.panel.AdaptivePanel();
        helpButton = new widgets.button.AdaptiveButton();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        okButton = new widgets.button.AdaptiveButton();
        cancelButton = new widgets.button.AdaptiveButton();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout(10, 10));

        westPanel.setLayout(new javax.swing.BoxLayout(westPanel, javax.swing.BoxLayout.PAGE_AXIS));

        adaptiveList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "General", "Chat", "Notifications", " ", " ", " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        adaptiveList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OnMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(adaptiveList1);

        westPanel.add(jScrollPane1);

        add(westPanel, java.awt.BorderLayout.WEST);

        centerPanel.setName("Panel.Border"); // NOI18N
        centerPanel.setLayout(new javax.swing.BoxLayout(centerPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(centerPanel, java.awt.BorderLayout.CENTER);

        south.setLayout(new java.awt.BorderLayout());

        hellpPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        helpButton.setText("Βοήθεια");
        helpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButtonActionPerformed(evt);
            }
        });
        hellpPanel.add(helpButton);

        south.add(hellpPanel, java.awt.BorderLayout.WEST);

        adaptivePanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));

        adaptivePanel1.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        adaptivePanel1.add(okButton);

        cancelButton.setText("Ακύρωση");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        adaptivePanel1.add(cancelButton);

        adaptivePanel2.add(adaptivePanel1);

        south.add(adaptivePanel2, java.awt.BorderLayout.EAST);

        add(south, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
		MainWindowPDA.showPanel(new PDAMainView());
	}//GEN-LAST:event_okButtonActionPerformed

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
		MainWindowPDA.showPanel(new PDAMainView());
	}//GEN-LAST:event_cancelButtonActionPerformed

	private void OnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OnMouseClicked
		if (evt.getClickCount() == 1 && evt.getButton() == MouseEvent.BUTTON1) {
			String value = (String)adaptiveList1.getSelectedValue();
			
			if (value.compareTo("General") == 0)
				showPanel(new GeneralSettingsPanel());
			else 
			if (value.compareTo("Notifications") == 0)
				showPanel(new NotificationsSettingsPanel());
			else
				showPanel(new ChatSettingsPanel());
		}
	}//GEN-LAST:event_OnMouseClicked

	private void helpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButtonActionPerformed
		MainWindowPDA.showPanel(new Help());
	}//GEN-LAST:event_helpButtonActionPerformed
		
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.list.AdaptiveList adaptiveList1;
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.button.AdaptiveButton cancelButton;
    private widgets.panel.AdaptivePanel centerPanel;
    private widgets.panel.AdaptivePanel hellpPanel;
    private widgets.button.AdaptiveButton helpButton;
    private javax.swing.JScrollPane jScrollPane1;
    private widgets.button.AdaptiveButton okButton;
    private widgets.panel.AdaptivePanel south;
    private widgets.panel.AdaptivePanel westPanel;
    // End of variables declaration//GEN-END:variables
}
