/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AccessibleIM.java
 *
 * Created on 25 Νοε 2011, 12:23:30 μμ
 */
package assignment2;

import javax.swing.JPanel;
import pc.MainWindowPC;

/**
 *
 * @author koutsop
 */
public class AccessibleIM extends javax.swing.JPanel {

    /** Creates new form AccessibleIM */
    public AccessibleIM() {
        initComponents();
        showPanel(new AdaptableIMView());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuContentsPanel = new widgets.panel.AdaptivePanel();
        menuPanel = new widgets.panel.AdaptivePanel();
        imButton = new widgets.button.MainMenuButton();
        settingsButton = new widgets.button.MainMenuButton();
        startPageButton = new widgets.button.MainMenuButton();
        mainMenuButton1 = new widgets.button.MainMenuButton();

        setMaximumSize(new java.awt.Dimension(1000, 688));
        setMinimumSize(new java.awt.Dimension(1000, 688));
        setPreferredSize(new java.awt.Dimension(1000, 688));
        setLayout(new java.awt.BorderLayout());

        menuContentsPanel.setLayout(new java.awt.GridLayout());
        add(menuContentsPanel, java.awt.BorderLayout.CENTER);

        imButton.setText("Accessible IM");
        imButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imButtonActionPerformed(evt);
            }
        });
        menuPanel.add(imButton);

        settingsButton.setText("Ρυθμίισεις");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        menuPanel.add(settingsButton);

        startPageButton.setText("Αρχική");
        startPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPageButtonActionPerformed(evt);
            }
        });
        menuPanel.add(startPageButton);

        mainMenuButton1.setText("Έξοδος");
        mainMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButton1ActionPerformed(evt);
            }
        });
        menuPanel.add(mainMenuButton1);

        add(menuPanel, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void showPanel(JPanel p) {
        menuContentsPanel.removeAll();
        p.setVisible(true);
        menuContentsPanel.add(p);
        menuContentsPanel.repaint();
        menuContentsPanel.validate();       
    }
    
    private void imButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imButtonActionPerformed
        showPanel(new AdaptableIMView());
    }//GEN-LAST:event_imButtonActionPerformed

    private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        showPanel(new AdaptableSettingsView());
    }//GEN-LAST:event_settingsButtonActionPerformed

    private void startPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPageButtonActionPerformed
        MainWindowPC.showPanel(new Login1());
    }//GEN-LAST:event_startPageButtonActionPerformed

    private void mainMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainMenuButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.MainMenuButton imButton;
    private widgets.button.MainMenuButton mainMenuButton1;
    private widgets.panel.AdaptivePanel menuContentsPanel;
    private widgets.panel.AdaptivePanel menuPanel;
    private widgets.button.MainMenuButton settingsButton;
    private widgets.button.MainMenuButton startPageButton;
    // End of variables declaration//GEN-END:variables
}
