/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Chat.java
 *
 * Created on 25 Νοε 2011, 11:44:48 πμ
 */
package assignment2;

import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class Chat extends javax.swing.JPanel {

    /** Creates new form Chat */
    public Chat(Dimension parentSize) {
        initComponents();
        
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
        int contactImgHeight = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("ContactImgHeight"));
		int contactImgWidth = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("ContactImgWidth"));
		int statusImgHeight = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("StatusImgHeight"));
		int statusImgWidth = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("StatusImgWidth"));
		
		assert	contactImgHeight	!= -1 && 
				contactImgWidth		!= -1 && 
				statusImgHeight		!= -1 && 
				statusImgWidth		!= -1;
        
        Utility.SetJComponentSize(avatarPanel, contactImgWidth, contactImgHeight);
        Utility.SetJComponentSize(statusAvatarPanel, statusImgWidth, statusImgHeight);
        
        //Utility.SetJComponentSize(imagePanel, new Dimension(100, 100));
        
        Utility.SetJComponentSize(this, parentSize); 
        
        String path = DMSLConnector.getInstance().getClient(false).Evaluate("VideoCallButton");
        videoCallButton.setIcon(new ImageIcon(getClass().getResource(path)));
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("CallButton");
        callButton.setIcon(new ImageIcon(getClass().getResource(path)));
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("SendFileButton");
        sendFileButton.setIcon(new ImageIcon(getClass().getResource(path)));
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("AddButton");
        addButton.setIcon(new ImageIcon(getClass().getResource(path)));  
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("CloseButton");
        closeButton.setIcon(new ImageIcon(getClass().getResource(path)));
        
        System.out.println(this.getPreferredSize());
    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendPanel = new widgets.panel.AdaptivePanel();
        chatButtonsPanel = new widgets.panel.AdaptivePanel();
        videoCallButton = new widgets.button.AdaptiveButton();
        callButton = new widgets.button.AdaptiveButton();
        sendFileButton = new widgets.button.AdaptiveButton();
        addButton = new widgets.button.AdaptiveButton();
        closeButton = new widgets.button.AdaptiveButton();
        chatPanel = new widgets.panel.AdaptivePanel();
        sendButonPanel = new widgets.panel.AdaptivePanel();
        sendButton = new widgets.button.AdaptiveButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        adaptiveTextBox2 = new widgets.textbox.AdaptiveTextBox();
        contactPanel = new widgets.panel.AdaptivePanel();
        avatarPanel = new widgets.panel.AdaptivePanel();
        statusPanel = new widgets.panel.AdaptivePanel();
        nameLabel = new widgets.label.AdaptiveLabel();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        statusAvatarPanel = new widgets.panel.AdaptivePanel();
        receivePanel = new widgets.panel.AdaptivePanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        scroolContentPanel = new widgets.panel.AdaptivePanel();
        conversationPanel1 = new widgets.panel.AdaptivePanel();
        imagePanel = new widgets.panel.AdaptivePanel();
        senderPanel = new widgets.panel.AdaptivePanel();
        nameLabel1 = new widgets.label.AdaptiveLabel();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        textTextField = new widgets.textfield.AdaptiveTextField();
        adaptivePanel4 = new widgets.panel.AdaptivePanel();
        timeStampLabel = new widgets.label.AdaptiveLabel();
        conversationPanel2 = new widgets.panel.AdaptivePanel();
        senderPanel1 = new widgets.panel.AdaptivePanel();

        setLayout(new java.awt.BorderLayout(0, 10));

        sendPanel.setLayout(new java.awt.BorderLayout(0, 5));

        chatButtonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 5));

        videoCallButton.setFunction("ChatButton");
        chatButtonsPanel.add(videoCallButton);

        callButton.setFunction("ChatButton");
        chatButtonsPanel.add(callButton);

        sendFileButton.setFunction("ChatButton");
        chatButtonsPanel.add(sendFileButton);

        addButton.setFunction("ChatButton");
        chatButtonsPanel.add(addButton);

        closeButton.setFunction("ChatButton");
        chatButtonsPanel.add(closeButton);

        sendPanel.add(chatButtonsPanel, java.awt.BorderLayout.NORTH);

        chatPanel.setLayout(new java.awt.BorderLayout(15, 15));

        sendButonPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));

        sendButton.setFunction("ChatButton");
        sendButton.setText("Send");
        sendButonPanel.add(sendButton);

        chatPanel.add(sendButonPanel, java.awt.BorderLayout.EAST);

        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        adaptiveTextBox2.setColumns(20);
        adaptiveTextBox2.setRows(5);
        jScrollPane1.setViewportView(adaptiveTextBox2);

        chatPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        sendPanel.add(chatPanel, java.awt.BorderLayout.CENTER);

        add(sendPanel, java.awt.BorderLayout.PAGE_END);

        contactPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        contactPanel.setMinimumSize(new java.awt.Dimension(125, 100));
        contactPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));

        avatarPanel.setFunction("ContactImg");
        avatarPanel.setName("ContactPanel.AvatarPanel"); // NOI18N
        contactPanel.add(avatarPanel);

        statusPanel.setLayout(new java.awt.BorderLayout());

        nameLabel.setText("koutsoppoulos Nikolaos: H zwh einai skata");
        statusPanel.add(nameLabel, java.awt.BorderLayout.PAGE_END);

        adaptivePanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        statusAvatarPanel.setFunction("StatusAvailableImg");
        statusAvatarPanel.setName("ContactPanel.StatusAvailablePanel"); // NOI18N
        statusAvatarPanel.setLayout(new javax.swing.BoxLayout(statusAvatarPanel, javax.swing.BoxLayout.LINE_AXIS));
        adaptivePanel1.add(statusAvatarPanel);

        statusPanel.add(adaptivePanel1, java.awt.BorderLayout.PAGE_START);

        contactPanel.add(statusPanel);

        add(contactPanel, java.awt.BorderLayout.PAGE_START);

        receivePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        receivePanel.setLayout(new javax.swing.BoxLayout(receivePanel, javax.swing.BoxLayout.LINE_AXIS));

        scroolContentPanel.setLayout(new java.awt.GridLayout(5, 1, 0, 20));

        conversationPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        conversationPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        imagePanel.setFunction("ReceiveContactImg");
        imagePanel.setMaximumSize(new java.awt.Dimension(50, 50));
        imagePanel.setMinimumSize(new java.awt.Dimension(50, 50));
        imagePanel.setName("Panel.ReceiveVideoPanel"); // NOI18N
        imagePanel.setPreferredSize(new java.awt.Dimension(50, 50));
        imagePanel.setLayout(new javax.swing.BoxLayout(imagePanel, javax.swing.BoxLayout.PAGE_AXIS));
        conversationPanel1.add(imagePanel);

        senderPanel.setLayout(new javax.swing.BoxLayout(senderPanel, javax.swing.BoxLayout.PAGE_AXIS));

        nameLabel1.setText("Marigianna:");
        senderPanel.add(nameLabel1);

        adaptivePanel2.setMaximumSize(new java.awt.Dimension(1, 10));
        adaptivePanel2.setMinimumSize(new java.awt.Dimension(1, 10));
        adaptivePanel2.setPreferredSize(new java.awt.Dimension(1, 10));

        javax.swing.GroupLayout adaptivePanel2Layout = new javax.swing.GroupLayout(adaptivePanel2);
        adaptivePanel2.setLayout(adaptivePanel2Layout);
        adaptivePanel2Layout.setHorizontalGroup(
            adaptivePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        adaptivePanel2Layout.setVerticalGroup(
            adaptivePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        senderPanel.add(adaptivePanel2);

        textTextField.setEditable(false);
        textTextField.setText("Bariemai na to 3ereis");
        senderPanel.add(textTextField);

        adaptivePanel4.setMaximumSize(new java.awt.Dimension(1, 10));
        adaptivePanel4.setMinimumSize(new java.awt.Dimension(1, 10));

        javax.swing.GroupLayout adaptivePanel4Layout = new javax.swing.GroupLayout(adaptivePanel4);
        adaptivePanel4.setLayout(adaptivePanel4Layout);
        adaptivePanel4Layout.setHorizontalGroup(
            adaptivePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        adaptivePanel4Layout.setVerticalGroup(
            adaptivePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        senderPanel.add(adaptivePanel4);

        timeStampLabel.setText("Sent at 12:03 PM on Sunday");
        senderPanel.add(timeStampLabel);

        conversationPanel1.add(senderPanel);

        scroolContentPanel.add(conversationPanel1);

        conversationPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        conversationPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        senderPanel1.setLayout(new java.awt.BorderLayout());
        conversationPanel2.add(senderPanel1);

        scroolContentPanel.add(conversationPanel2);

        jScrollPane2.setViewportView(scroolContentPanel);

        receivePanel.add(jScrollPane2);

        add(receivePanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.panel.AdaptivePanel adaptivePanel4;
    private widgets.textbox.AdaptiveTextBox adaptiveTextBox2;
    private widgets.button.AdaptiveButton addButton;
    private widgets.panel.AdaptivePanel avatarPanel;
    private widgets.button.AdaptiveButton callButton;
    private widgets.panel.AdaptivePanel chatButtonsPanel;
    private widgets.panel.AdaptivePanel chatPanel;
    private widgets.button.AdaptiveButton closeButton;
    private widgets.panel.AdaptivePanel contactPanel;
    private widgets.panel.AdaptivePanel conversationPanel1;
    private widgets.panel.AdaptivePanel conversationPanel2;
    private widgets.panel.AdaptivePanel imagePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private widgets.label.AdaptiveLabel nameLabel;
    private widgets.label.AdaptiveLabel nameLabel1;
    private widgets.panel.AdaptivePanel receivePanel;
    private widgets.panel.AdaptivePanel scroolContentPanel;
    private widgets.panel.AdaptivePanel sendButonPanel;
    private widgets.button.AdaptiveButton sendButton;
    private widgets.button.AdaptiveButton sendFileButton;
    private widgets.panel.AdaptivePanel sendPanel;
    private widgets.panel.AdaptivePanel senderPanel;
    private widgets.panel.AdaptivePanel senderPanel1;
    private widgets.panel.AdaptivePanel statusAvatarPanel;
    private widgets.panel.AdaptivePanel statusPanel;
    private widgets.textfield.AdaptiveTextField textTextField;
    private widgets.label.AdaptiveLabel timeStampLabel;
    private widgets.button.AdaptiveButton videoCallButton;
    // End of variables declaration//GEN-END:variables
}
