/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Contact.java
 *
 * Created on 24 Νοε 2011, 10:06:01 πμ
 */
package assignment2;

import java.awt.Dimension;

/**
 *
 * @author koutsop
 */
public class Contact extends javax.swing.JPanel {
    private String statusType;
	/** Creates new form Contact */
	public Contact(
		String avatarFunction,
		String statusFunction,
		String contactName,
		String contactSatus,
        String statusType
	) {
		initComponents();
        this.statusType = statusType;
		avatarPanel.setFunction(avatarFunction);
		statusAvailablePanel.setFunction(statusFunction);
		nameLabel.setText(contactName);
		statusLabel.setText(contactSatus);
	}
    
    public void SetContactSize (int width, int height){
        this.setMinimumSize(new Dimension(width, height));
        this.setMaximumSize(new Dimension(width, height));
        this.setPreferredSize(new Dimension(width, height));
    }
	
    public void SetAvatarDimensionPanel (int width, int height) {
        avatarPanel.setMinimumSize(new Dimension(width, height));
        avatarPanel.setMaximumSize(new Dimension(width, height));
        avatarPanel.setPreferredSize(new Dimension(width, height));
    }
    
    public void SetStatusDimensionPanel (int width, int height) {
        widgets.panel.AdaptivePanel p;
        
        if ("available".equals(statusType))
            p = statusAvailablePanel;
        else
        if ("busy".equals(statusType))
            p = statusBusyPanel;
        else
            p = statusIdlePanel;
        
        p.setMinimumSize(new Dimension(width, height));
        p.setMaximumSize(new Dimension(width, height));
        p.setPreferredSize(new Dimension(width, height));
    }  
    
	public widgets.panel.AdaptivePanel GetAvatarPanel () 
		{ return avatarPanel; }
	
	public widgets.panel.AdaptivePanel GetStatusPanel () 
		{ return statusAvailablePanel; }	

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        avatarPanel = new widgets.panel.AdaptivePanel();
        statusAvailablePanel = new widgets.panel.AdaptivePanel();
        statusBusyPanel = new widgets.panel.AdaptivePanel();
        statusIdlePanel = new widgets.panel.AdaptivePanel();
        namePanel = new widgets.panel.AdaptivePanel();
        nameLabel = new widgets.label.AdaptiveLabel();
        statusLabel = new widgets.label.AdaptiveLabel();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        avatarPanel.setMaximumSize(new java.awt.Dimension(0, 0));
        avatarPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        avatarPanel.setName("ContactPanel.AvatarPanel"); // NOI18N
        avatarPanel.setPreferredSize(new java.awt.Dimension(0, 0));
        avatarPanel.setLayout(new javax.swing.BoxLayout(avatarPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(avatarPanel);

        statusAvailablePanel.setName("ContactPanel.StatusAvailablePanel"); // NOI18N
        statusAvailablePanel.setLayout(new javax.swing.BoxLayout(statusAvailablePanel, javax.swing.BoxLayout.LINE_AXIS));
        add(statusAvailablePanel);

        statusBusyPanel.setName("ContactPanel.StatusBusyPanel"); // NOI18N
        statusBusyPanel.setLayout(new javax.swing.BoxLayout(statusBusyPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(statusBusyPanel);

        statusIdlePanel.setName("ContactPanel.StatusIdlePanel"); // NOI18N
        statusIdlePanel.setLayout(new javax.swing.BoxLayout(statusIdlePanel, javax.swing.BoxLayout.LINE_AXIS));
        add(statusIdlePanel);

        namePanel.setLayout(new javax.swing.BoxLayout(namePanel, javax.swing.BoxLayout.PAGE_AXIS));
        namePanel.add(nameLabel);
        namePanel.add(statusLabel);

        add(namePanel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.panel.AdaptivePanel avatarPanel;
    private widgets.label.AdaptiveLabel nameLabel;
    private widgets.panel.AdaptivePanel namePanel;
    private widgets.panel.AdaptivePanel statusAvailablePanel;
    private widgets.panel.AdaptivePanel statusBusyPanel;
    private widgets.panel.AdaptivePanel statusIdlePanel;
    private widgets.label.AdaptiveLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
