package demo;


import java.awt.CardLayout;
import javax.swing.JPanel;
import utilities.Adaptation;
import utilities.DMSLConnector;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdaptableView.java
 *
 * Created on 26 Οκτ 2010, 5:28:27 μμ
 */

/**
 *
 * @author leonidis
 */
public class AdaptableView extends javax.swing.JPanel {

    final static String viewA = "ViewA";
    final static String viewB = "ViewB";
    JPanel p = new JPanel(new CardLayout());

    /** Creates new form AdaptableView */
    public AdaptableView() {
        initComponents();
        
        p.add(new ViewA(), viewA);
        p.add(new ViewB(), viewB);
        this.add(p);

        CardLayout cl = (CardLayout)(p.getLayout());
        String pid = DMSLConnector.getInstance().getClient(false).Evaluate("AdaptableView1");
        System.out.println("View:" + pid);
        cl.show(p, pid);
        p.revalidate();
        
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
        this.updateUI();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adaptationLogger1 = new utilities.AdaptationLogger();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utilities.AdaptationLogger adaptationLogger1;
    // End of variables declaration//GEN-END:variables

}
