package demo;


import javax.swing.SwingConstants;
import pc.MainWindowPC;
import utilities.Adaptation;
import utilities.DMSLConnector;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RestaurantDemo.java
 *
 * Created on 26 Οκτ 2010, 10:57:06 πμ
 */

/**
 *
 * @author leonidis
 */
public class RestaurantDemo extends javax.swing.JPanel {

    /** Creates new form RestaurantDemo */
    public RestaurantDemo() {

        initComponents();

        /*Update specific components so as to impose specific rules (both methods take as argument
         the  main container/placeholder the holds all the widgets placed into the UI. This concept
         is similar to the HTML <body> element) */
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
        this.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adaptivePanel16 = new widgets.panel.AdaptivePanel();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        adaptiveButton1 = new widgets.button.AdaptiveButton();
        adaptiveButton2 = new widgets.button.AdaptiveButton();
        adaptiveButton3 = new widgets.button.AdaptiveButton();
        adaptivePanel6 = new widgets.panel.AdaptivePanel();
        adaptiveLabel1 = new widgets.label.AdaptiveLabel();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        adaptivePanel3 = new widgets.panel.AdaptivePanel();
        adaptivePanel7 = new widgets.panel.AdaptivePanel();
        gsPanel = new widgets.panel.AdaptivePanel();
        adaptiveLabel2 = new widgets.label.AdaptiveLabel();
        adaptivePanel14 = new widgets.panel.AdaptivePanel();
        adaptivePanel15 = new widgets.panel.AdaptivePanel();
        adaptiveLabel11 = new widgets.label.AdaptiveLabel();
        adaptiveLabel12 = new widgets.label.AdaptiveLabel();
        adaptiveButton4 = new widgets.button.AdaptiveButton();
        adaptivePanel4 = new widgets.panel.AdaptivePanel();
        adaptivePanel8 = new widgets.panel.AdaptivePanel();
        gsPanel1 = new widgets.panel.AdaptivePanel();
        adaptiveLabel3 = new widgets.label.AdaptiveLabel();
        adaptivePanel9 = new widgets.panel.AdaptivePanel();
        adaptivePanel12 = new widgets.panel.AdaptivePanel();
        adaptiveLabel8 = new widgets.label.AdaptiveLabel();
        adaptiveLabel7 = new widgets.label.AdaptiveLabel();
        adaptiveButton5 = new widgets.button.AdaptiveButton();
        adaptivePanel5 = new widgets.panel.AdaptivePanel();
        adaptivePanel10 = new widgets.panel.AdaptivePanel();
        gsPanel2 = new widgets.panel.AdaptivePanel();
        adaptiveLabel4 = new widgets.label.AdaptiveLabel();
        adaptivePanel11 = new widgets.panel.AdaptivePanel();
        adaptivePanel13 = new widgets.panel.AdaptivePanel();
        adaptiveLabel9 = new widgets.label.AdaptiveLabel();
        adaptiveLabel10 = new widgets.label.AdaptiveLabel();
        adaptiveButton6 = new widgets.button.AdaptiveButton();

        setLayout(new java.awt.BorderLayout());

        adaptivePanel16.setLayout(new java.awt.BorderLayout());

        adaptivePanel1.setPreferredSize(new java.awt.Dimension(366, 90));
        adaptivePanel1.setLayout(new java.awt.GridLayout(1, 0));

        adaptiveButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Picture2.png"))); // NOI18N
        adaptiveButton1.setHorizontalTextPosition(0);
        adaptiveButton1.setText("Back");
        adaptiveButton1.setVerifyInputWhenFocusTarget(false);
        adaptiveButton1.setVerticalTextPosition(3);
        adaptivePanel1.add(adaptiveButton1);

        adaptiveButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Picture3.png"))); // NOI18N
        adaptiveButton2.setHorizontalTextPosition(0);
        adaptiveButton2.setText("Home");
        adaptiveButton2.setVerifyInputWhenFocusTarget(false);
        adaptiveButton2.setVerticalTextPosition(3);
        adaptivePanel1.add(adaptiveButton2);

        adaptiveButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Picture4.png"))); // NOI18N
        adaptiveButton3.setHorizontalTextPosition(0);
        adaptiveButton3.setText("Help");
        adaptiveButton3.setVerticalTextPosition(3);
        adaptivePanel1.add(adaptiveButton3);

        adaptivePanel16.add(adaptivePanel1, java.awt.BorderLayout.EAST);

        add(adaptivePanel16, java.awt.BorderLayout.NORTH);

        adaptivePanel6.setLayout(new java.awt.BorderLayout());

        adaptiveLabel1.setFunction("MainTitle");
        adaptiveLabel1.setText("Starters");
        adaptivePanel6.add(adaptiveLabel1, java.awt.BorderLayout.NORTH);

        adaptivePanel2.setPreferredSize(new java.awt.Dimension(676, 180));
        adaptivePanel2.setLayout(new java.awt.GridLayout(3, 0, 0, 5));

        adaptivePanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        adaptivePanel3.setPreferredSize(new java.awt.Dimension(533, 84));
        adaptivePanel3.setLayout(new java.awt.GridLayout(1, 0));

        adaptivePanel7.setLayout(new javax.swing.BoxLayout(adaptivePanel7, javax.swing.BoxLayout.LINE_AXIS));

        gsPanel.setFunction("greekSaladImg");

        javax.swing.GroupLayout gsPanelLayout = new javax.swing.GroupLayout(gsPanel);
        gsPanel.setLayout(gsPanelLayout);
        gsPanelLayout.setHorizontalGroup(
            gsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        gsPanelLayout.setVerticalGroup(
            gsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        adaptivePanel7.add(gsPanel);

        adaptivePanel3.add(adaptivePanel7);

        adaptiveLabel2.setFunction("AppetizerName");
        adaptiveLabel2.setText("Greek Salad");
        adaptivePanel3.add(adaptiveLabel2);

        adaptivePanel14.setBackground(new java.awt.Color(236, 250, 250));

        adaptivePanel15.setLayout(new java.awt.GridLayout(2, 1));

        adaptiveLabel11.setText("Tomato, cucumber, bell ");
        adaptivePanel15.add(adaptiveLabel11);

        adaptiveLabel12.setText("pepper, olives, olive oil… ");
        adaptivePanel15.add(adaptiveLabel12);

        javax.swing.GroupLayout adaptivePanel14Layout = new javax.swing.GroupLayout(adaptivePanel14);
        adaptivePanel14.setLayout(adaptivePanel14Layout);
        adaptivePanel14Layout.setHorizontalGroup(
            adaptivePanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adaptivePanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        adaptivePanel14Layout.setVerticalGroup(
            adaptivePanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adaptivePanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        adaptivePanel3.add(adaptivePanel14);

        adaptiveButton4.setText("Igredients");
        adaptiveButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton4ActionPerformed(evt);
            }
        });
        adaptivePanel3.add(adaptiveButton4);

        adaptivePanel2.add(adaptivePanel3);

        adaptivePanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        adaptivePanel4.setLayout(new java.awt.GridLayout(1, 0));

        adaptivePanel8.setLayout(new javax.swing.BoxLayout(adaptivePanel8, javax.swing.BoxLayout.LINE_AXIS));

        gsPanel1.setFunction("gardenSaladImg");

        javax.swing.GroupLayout gsPanel1Layout = new javax.swing.GroupLayout(gsPanel1);
        gsPanel1.setLayout(gsPanel1Layout);
        gsPanel1Layout.setHorizontalGroup(
            gsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        gsPanel1Layout.setVerticalGroup(
            gsPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        adaptivePanel8.add(gsPanel1);

        adaptivePanel4.add(adaptivePanel8);

        adaptiveLabel3.setFunction("AppetizerName");
        adaptiveLabel3.setText("Garden Salad");
        adaptivePanel4.add(adaptiveLabel3);

        adaptivePanel9.setBackground(new java.awt.Color(236, 250, 250));

        adaptivePanel12.setLayout(new java.awt.GridLayout(2, 1));

        adaptiveLabel8.setText("Lettuce, green ");
        adaptivePanel12.add(adaptiveLabel8);

        adaptiveLabel7.setText("vegetables, light dressing");
        adaptivePanel12.add(adaptiveLabel7);

        javax.swing.GroupLayout adaptivePanel9Layout = new javax.swing.GroupLayout(adaptivePanel9);
        adaptivePanel9.setLayout(adaptivePanel9Layout);
        adaptivePanel9Layout.setHorizontalGroup(
            adaptivePanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adaptivePanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        adaptivePanel9Layout.setVerticalGroup(
            adaptivePanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adaptivePanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        adaptivePanel4.add(adaptivePanel9);

        adaptiveButton5.setText("Igredients");
        adaptivePanel4.add(adaptiveButton5);

        adaptivePanel2.add(adaptivePanel4);

        adaptivePanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        adaptivePanel5.setLayout(new java.awt.GridLayout(1, 0));

        adaptivePanel10.setLayout(new javax.swing.BoxLayout(adaptivePanel10, javax.swing.BoxLayout.LINE_AXIS));

        gsPanel2.setFunction("onionSaladImg");

        javax.swing.GroupLayout gsPanel2Layout = new javax.swing.GroupLayout(gsPanel2);
        gsPanel2.setLayout(gsPanel2Layout);
        gsPanel2Layout.setHorizontalGroup(
            gsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 224, Short.MAX_VALUE)
        );
        gsPanel2Layout.setVerticalGroup(
            gsPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 95, Short.MAX_VALUE)
        );

        adaptivePanel10.add(gsPanel2);

        adaptivePanel5.add(adaptivePanel10);

        adaptiveLabel4.setFunction("AppetizerName");
        adaptiveLabel4.setText("Onion Rings");
        adaptivePanel5.add(adaptiveLabel4);

        adaptivePanel11.setBackground(new java.awt.Color(236, 250, 250));

        adaptivePanel13.setLayout(new java.awt.GridLayout(2, 1));

        adaptiveLabel9.setText("Onion rings fried in olive ");
        adaptivePanel13.add(adaptiveLabel9);

        adaptiveLabel10.setText("oil, with tomato dressing ");
        adaptivePanel13.add(adaptiveLabel10);

        javax.swing.GroupLayout adaptivePanel11Layout = new javax.swing.GroupLayout(adaptivePanel11);
        adaptivePanel11.setLayout(adaptivePanel11Layout);
        adaptivePanel11Layout.setHorizontalGroup(
            adaptivePanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adaptivePanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        adaptivePanel11Layout.setVerticalGroup(
            adaptivePanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adaptivePanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        adaptivePanel5.add(adaptivePanel11);

        adaptiveButton6.setText("Igredients");
        adaptivePanel5.add(adaptiveButton6);

        adaptivePanel2.add(adaptivePanel5);

        adaptivePanel6.add(adaptivePanel2, java.awt.BorderLayout.CENTER);

        add(adaptivePanel6, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void adaptiveButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton4ActionPerformed
	
	AdaptableView av = new AdaptableView();       
        MainWindowPC.showPanel(av);
	
    }//GEN-LAST:event_adaptiveButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.AdaptiveButton adaptiveButton1;
    private widgets.button.AdaptiveButton adaptiveButton2;
    private widgets.button.AdaptiveButton adaptiveButton3;
    private widgets.button.AdaptiveButton adaptiveButton4;
    private widgets.button.AdaptiveButton adaptiveButton5;
    private widgets.button.AdaptiveButton adaptiveButton6;
    private widgets.label.AdaptiveLabel adaptiveLabel1;
    private widgets.label.AdaptiveLabel adaptiveLabel10;
    private widgets.label.AdaptiveLabel adaptiveLabel11;
    private widgets.label.AdaptiveLabel adaptiveLabel12;
    private widgets.label.AdaptiveLabel adaptiveLabel2;
    private widgets.label.AdaptiveLabel adaptiveLabel3;
    private widgets.label.AdaptiveLabel adaptiveLabel4;
    private widgets.label.AdaptiveLabel adaptiveLabel7;
    private widgets.label.AdaptiveLabel adaptiveLabel8;
    private widgets.label.AdaptiveLabel adaptiveLabel9;
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel10;
    private widgets.panel.AdaptivePanel adaptivePanel11;
    private widgets.panel.AdaptivePanel adaptivePanel12;
    private widgets.panel.AdaptivePanel adaptivePanel13;
    private widgets.panel.AdaptivePanel adaptivePanel14;
    private widgets.panel.AdaptivePanel adaptivePanel15;
    private widgets.panel.AdaptivePanel adaptivePanel16;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.panel.AdaptivePanel adaptivePanel3;
    private widgets.panel.AdaptivePanel adaptivePanel4;
    private widgets.panel.AdaptivePanel adaptivePanel5;
    private widgets.panel.AdaptivePanel adaptivePanel6;
    private widgets.panel.AdaptivePanel adaptivePanel7;
    private widgets.panel.AdaptivePanel adaptivePanel8;
    private widgets.panel.AdaptivePanel adaptivePanel9;
    private widgets.panel.AdaptivePanel gsPanel;
    private widgets.panel.AdaptivePanel gsPanel1;
    private widgets.panel.AdaptivePanel gsPanel2;
    // End of variables declaration//GEN-END:variables

}
