/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VideoCall.java
 *
 * Created on 29 Νοε 2011, 12:49:20 πμ
 */
package assignment2.Spots;

import Utility.Utility;
import assignment2.VideoChat;
import java.awt.FlowLayout;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class VideoCall extends javax.swing.JPanel {

    /** Creates new form VideoCall */
    public VideoCall() {
        initComponents();
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);

        int size = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("sendVideoImagePanel"));
        Utility.SetJComponentSize(marigiannaPanel, size, size);
		Utility.SetJComponentSize(koutsopPanel, size, size);
                
		VideoChat chat = new VideoChat();
		((FlowLayout)chat.getButtonsPanel().getLayout()).setAlignment(FlowLayout.RIGHT);
        chat.setVisible(true);
        
		chatPanel.add(chat);
    }

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        callPanel = new widgets.panel.AdaptivePanel();
        gapPanel = new widgets.panel.AdaptivePanel();
        marigiannaPanel = new widgets.panel.AdaptivePanel();
        myPanel = new widgets.panel.AdaptivePanel();
        adaptivePanel4 = new widgets.panel.AdaptivePanel();
        koutsopPanel = new widgets.panel.AdaptivePanel();
        chatPanel = new widgets.panel.AdaptivePanel();

        setLayout(new java.awt.GridLayout(3, 1, 0, 10));

        callPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 0));
        callPanel.setLayout(new java.awt.BorderLayout());

        gapPanel.setLayout(new javax.swing.BoxLayout(gapPanel, javax.swing.BoxLayout.LINE_AXIS));
        callPanel.add(gapPanel, java.awt.BorderLayout.CENTER);

        marigiannaPanel.setFunction("marigiannaImg");
        marigiannaPanel.setName("Panel.Content.MarigiannaImage"); // NOI18N

        javax.swing.GroupLayout marigiannaPanelLayout = new javax.swing.GroupLayout(marigiannaPanel);
        marigiannaPanel.setLayout(marigiannaPanelLayout);
        marigiannaPanelLayout.setHorizontalGroup(
            marigiannaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        marigiannaPanelLayout.setVerticalGroup(
            marigiannaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        callPanel.add(marigiannaPanel, java.awt.BorderLayout.EAST);

        add(callPanel);

        myPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout adaptivePanel4Layout = new javax.swing.GroupLayout(adaptivePanel4);
        adaptivePanel4.setLayout(adaptivePanel4Layout);
        adaptivePanel4Layout.setHorizontalGroup(
            adaptivePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        adaptivePanel4Layout.setVerticalGroup(
            adaptivePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        myPanel.add(adaptivePanel4, java.awt.BorderLayout.CENTER);

        koutsopPanel.setFunction("koutsopImg");
        koutsopPanel.setName("Panel.Content.KoutsopImage"); // NOI18N

        javax.swing.GroupLayout koutsopPanelLayout = new javax.swing.GroupLayout(koutsopPanel);
        koutsopPanel.setLayout(koutsopPanelLayout);
        koutsopPanelLayout.setHorizontalGroup(
            koutsopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        koutsopPanelLayout.setVerticalGroup(
            koutsopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
        );

        myPanel.add(koutsopPanel, java.awt.BorderLayout.EAST);

        add(myPanel);

        chatPanel.setLayout(new javax.swing.BoxLayout(chatPanel, javax.swing.BoxLayout.LINE_AXIS));
        add(chatPanel);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.panel.AdaptivePanel adaptivePanel4;
    private widgets.panel.AdaptivePanel callPanel;
    private widgets.panel.AdaptivePanel chatPanel;
    private widgets.panel.AdaptivePanel gapPanel;
    private widgets.panel.AdaptivePanel koutsopPanel;
    private widgets.panel.AdaptivePanel marigiannaPanel;
    private widgets.panel.AdaptivePanel myPanel;
    // End of variables declaration//GEN-END:variables
}
