/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdaptableIMMainView.java
 *
 * Created on 1 Δεκ 2011, 1:44:35 πμ
 */
package AdaptableWindows;

import assignment2.AccessibleIM;
import assignment2.Instability.InstabilityAccessibleIM;
import java.awt.CardLayout;
import javax.swing.JPanel;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class AdaptableIMMainView extends javax.swing.JPanel {
    
	final static String viewA = "CommonMainView";
    final static String viewB = "InstabilityMainView";
	final static String viewC = "PDAMainView";
    JPanel p = new JPanel(new CardLayout());
	
	/** Creates new form AdaptableIMMainView */
	public AdaptableIMMainView() {
		initComponents();
        
		p.add(new AccessibleIM(), viewA);
        p.add(new InstabilityAccessibleIM(), viewB);
		p.add(new InstabilityAccessibleIM(), viewC);	//Edw 8elw to pda
        this.add(p);

        CardLayout cl = (CardLayout)(p.getLayout());
        String pid = DMSLConnector.getInstance().getClient(false).Evaluate("MainIMView");
        System.out.println("Main View:" + pid);
        cl.show(p, pid);
        p.revalidate();
        
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
        this.updateUI();	
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
