/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GeneralSettingsPanel.java
 *
 * Created on 3 Δεκ 2011, 4:39:55 μμ
 */
package assignment2.LowVision;

import utilities.Adaptation;

/**
 *
 * @author koutsop
 */
public class GeneralSettingsPanel extends javax.swing.JPanel {

	/** Creates new form GeneralSettingsPanel */
	public GeneralSettingsPanel() {
		initComponents();
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);			
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        northPanel = new widgets.panel.AdaptivePanel();
        startupCheckBox = new widgets.checkbox.AdaptiveCheckBox();
        adaptivePanel15 = new widgets.panel.AdaptivePanel();
        adaptiveCheckBox1 = new widgets.checkbox.AdaptiveCheckBox();
        centalPanel = new widgets.panel.AdaptivePanel();
        fontsPanel = new widgets.panel.AdaptivePanel();
        fontPanel = new widgets.panel.AdaptivePanel();
        adaptiveLabel1 = new widgets.label.AdaptiveLabel();
        adaptiveComboBox1 = new widgets.combobox.AdaptiveComboBox();
        stylePanel = new widgets.panel.AdaptivePanel();
        adaptiveLabel2 = new widgets.label.AdaptiveLabel();
        adaptiveComboBox2 = new widgets.combobox.AdaptiveComboBox();
        sizePanel = new widgets.panel.AdaptivePanel();
        adaptiveLabel3 = new widgets.label.AdaptiveLabel();
        adaptiveSpinner1 = new widgets.spinner.AdaptiveSpinner();
        southPanel = new widgets.panel.AdaptivePanel();
        previewLabel = new widgets.label.AdaptiveLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 20, 0, 0));
        setMaximumSize(new java.awt.Dimension(307, 169));
        setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        adaptivePanel1.setMaximumSize(new java.awt.Dimension(307, 169));
        adaptivePanel1.setLayout(new java.awt.BorderLayout());

        northPanel.setLayout(new javax.swing.BoxLayout(northPanel, javax.swing.BoxLayout.PAGE_AXIS));

        startupCheckBox.setHorizontalAlignment(0);
        startupCheckBox.setText("Έναρξη εφαρμογής κατά την εκκίνηση");
        northPanel.add(startupCheckBox);

        adaptivePanel15.setMaximumSize(new java.awt.Dimension(1, 15));
        adaptivePanel15.setMinimumSize(new java.awt.Dimension(1, 15));

        javax.swing.GroupLayout adaptivePanel15Layout = new javax.swing.GroupLayout(adaptivePanel15);
        adaptivePanel15.setLayout(adaptivePanel15Layout);
        adaptivePanel15Layout.setHorizontalGroup(
            adaptivePanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );
        adaptivePanel15Layout.setVerticalGroup(
            adaptivePanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        northPanel.add(adaptivePanel15);

        adaptiveCheckBox1.setText("adaptiveCheckBox1");
        northPanel.add(adaptiveCheckBox1);

        adaptivePanel1.add(northPanel, java.awt.BorderLayout.NORTH);

        centalPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        fontsPanel.setLayout(new java.awt.GridLayout(3, 1, 0, 20));

        fontPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        adaptiveLabel1.setText("Γραμματοσειρά: ");
        fontPanel.add(adaptiveLabel1);

        adaptiveComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arial", "Comic Sans MS", "Dialog", "Magneto", "Papyrus", "Times New Roman", "" }));
        fontPanel.add(adaptiveComboBox1);

        fontsPanel.add(fontPanel);

        stylePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        adaptiveLabel2.setText("Στύλ: ");
        stylePanel.add(adaptiveLabel2);

        adaptiveComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plain", "Bold", "Italic", "Bold Italic" }));
        stylePanel.add(adaptiveComboBox2);

        fontsPanel.add(stylePanel);

        sizePanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        adaptiveLabel3.setText("Μέγεθος: ");
        sizePanel.add(adaptiveLabel3);

        adaptiveSpinner1.setValue(40);
        sizePanel.add(adaptiveSpinner1);

        fontsPanel.add(sizePanel);

        centalPanel.add(fontsPanel);

        adaptivePanel1.add(centalPanel, java.awt.BorderLayout.CENTER);

        previewLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 40));
        previewLabel.setText("Έτσι θα φαίνεται το κείμενό σας!");
        southPanel.add(previewLabel);

        adaptivePanel1.add(southPanel, java.awt.BorderLayout.SOUTH);

        add(adaptivePanel1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.checkbox.AdaptiveCheckBox adaptiveCheckBox1;
    private widgets.combobox.AdaptiveComboBox adaptiveComboBox1;
    private widgets.combobox.AdaptiveComboBox adaptiveComboBox2;
    private widgets.label.AdaptiveLabel adaptiveLabel1;
    private widgets.label.AdaptiveLabel adaptiveLabel2;
    private widgets.label.AdaptiveLabel adaptiveLabel3;
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel15;
    private widgets.spinner.AdaptiveSpinner adaptiveSpinner1;
    private widgets.panel.AdaptivePanel centalPanel;
    private widgets.panel.AdaptivePanel fontPanel;
    private widgets.panel.AdaptivePanel fontsPanel;
    private widgets.panel.AdaptivePanel northPanel;
    private widgets.label.AdaptiveLabel previewLabel;
    private widgets.panel.AdaptivePanel sizePanel;
    private widgets.panel.AdaptivePanel southPanel;
    private widgets.checkbox.AdaptiveCheckBox startupCheckBox;
    private widgets.panel.AdaptivePanel stylePanel;
    // End of variables declaration//GEN-END:variables
}
