/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Chat.java
 *
 * Created on 2 Νοε 2011, 18:03:48 μμ
 */
package assignment2.pda;

import assignment2.Utility.Utility;
import javax.swing.ImageIcon;
import pda.MainWindowPDA;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class Chat extends javax.swing.JPanel {
	private boolean isVisible = false;
    /** Creates new form Chat */
    public Chat() {
        initComponents();
        
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
        int contactImgHeight = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("ContactImgHeight"));
		int contactImgWidth = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("ContactImgWidth"));
		int statusImgHeight = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("StatusImgHeight"));
		int statusImgWidth = Integer.parseInt(DMSLConnector.getInstance().getClient(false).Evaluate("StatusImgWidth"));
		
		assert	contactImgHeight	!= -1 && 
				contactImgWidth		!= -1 && 
				statusImgHeight		!= -1 && 
				statusImgWidth		!= -1;
        
        Utility.SetJComponentSize(avatarPanel, contactImgWidth, contactImgHeight);
        Utility.SetJComponentSize(statusAvatarPanel, statusImgWidth, statusImgHeight);
        
        String path = DMSLConnector.getInstance().getClient(false).Evaluate("VideoCallButton");
        videoCallButton.setIcon(new ImageIcon(getClass().getResource(path)));
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("CallButton");
        callButton.setIcon(new ImageIcon(getClass().getResource(path)));
            
        path = DMSLConnector.getInstance().getClient(false).Evaluate("AddButton");
        addButton.setIcon(new ImageIcon(getClass().getResource(path)));  
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("CloseButton");
        closeButton.setIcon(new ImageIcon(getClass().getResource(path)));
		
        path = DMSLConnector.getInstance().getClient(false).Evaluate("ArrowUpButton");
        adaptiveButton20.setIcon(new ImageIcon(getClass().getResource(path)));		
		
		SetPreferencesButtonsVisibility(false);
    }
	
	private void SetPreferencesButtonsVisibility (boolean b) {
		videoCallButton.setVisible(b);
		callButton.setVisible(b);
		addButton.setVisible(b);
		closeButton.setVisible(b);
	}
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contactPanel = new widgets.panel.AdaptivePanel();
        adaptivePanel6 = new widgets.panel.AdaptivePanel();
        avatarPanel = new widgets.panel.AdaptivePanel();
        statusPanel = new widgets.panel.AdaptivePanel();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        statusAvatarPanel = new widgets.panel.AdaptivePanel();
        adaptiveButton32 = new widgets.button.AdaptiveButton();
        nameLabel = new widgets.label.AdaptiveLabel();
        chatButtonsPanel = new widgets.panel.AdaptivePanel();
        videoCallButton = new widgets.button.AdaptiveButton();
        callButton = new widgets.button.AdaptiveButton();
        addButton = new widgets.button.AdaptiveButton();
        closeButton = new widgets.button.AdaptiveButton();
        receivePanel = new widgets.panel.AdaptivePanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        scroolContentPanel = new widgets.panel.AdaptivePanel();
        conversationKoutsopPanel = new widgets.panel.AdaptivePanel();
        senderPanel2 = new widgets.panel.AdaptivePanel();
        northPanel1 = new widgets.panel.AdaptivePanel();
        senderInfoPanel2 = new widgets.panel.AdaptivePanel();
        senderImagePanel1 = new widgets.panel.AdaptivePanel();
        senderInfoPanel3 = new widgets.panel.AdaptivePanel();
        senderNameLabel1 = new widgets.label.AdaptiveLabel();
        timeLabel1 = new widgets.label.AdaptiveLabel();
        senderTextPanel1 = new widgets.panel.AdaptivePanel();
        adaptiveLabel3 = new widgets.label.AdaptiveLabel();
        conversationMarigiannaPanel = new widgets.panel.AdaptivePanel();
        senderPanel1 = new widgets.panel.AdaptivePanel();
        northPanel = new widgets.panel.AdaptivePanel();
        senderInfoPanel1 = new widgets.panel.AdaptivePanel();
        senderImagePanel = new widgets.panel.AdaptivePanel();
        senderInfoPanel = new widgets.panel.AdaptivePanel();
        senderNameLabel = new widgets.label.AdaptiveLabel();
        timeLabel = new widgets.label.AdaptiveLabel();
        senderTextPanel = new widgets.panel.AdaptivePanel();
        adaptiveLabel2 = new widgets.label.AdaptiveLabel();
        adaptiveLabel1 = new widgets.label.AdaptiveLabel();
        conversationKoutsopPanel1 = new widgets.panel.AdaptivePanel();
        senderPanel3 = new widgets.panel.AdaptivePanel();
        northPanel2 = new widgets.panel.AdaptivePanel();
        senderInfoPanel4 = new widgets.panel.AdaptivePanel();
        senderImagePanel2 = new widgets.panel.AdaptivePanel();
        senderInfoPanel5 = new widgets.panel.AdaptivePanel();
        senderNameLabel2 = new widgets.label.AdaptiveLabel();
        timeLabel2 = new widgets.label.AdaptiveLabel();
        senderTextPanel2 = new widgets.panel.AdaptivePanel();
        adaptiveLabel4 = new widgets.label.AdaptiveLabel();
        conversationMarigiannaPanel1 = new widgets.panel.AdaptivePanel();
        senderPanel4 = new widgets.panel.AdaptivePanel();
        northPanel3 = new widgets.panel.AdaptivePanel();
        senderInfoPanel6 = new widgets.panel.AdaptivePanel();
        senderImagePanel3 = new widgets.panel.AdaptivePanel();
        senderInfoPanel7 = new widgets.panel.AdaptivePanel();
        senderNameLabel3 = new widgets.label.AdaptiveLabel();
        timeLabel3 = new widgets.label.AdaptiveLabel();
        senderTextPanel3 = new widgets.panel.AdaptivePanel();
        adaptiveLabel5 = new widgets.label.AdaptiveLabel();
        adaptiveLabel6 = new widgets.label.AdaptiveLabel();
        conversationMarigiannaPanel2 = new widgets.panel.AdaptivePanel();
        senderPanel5 = new widgets.panel.AdaptivePanel();
        northPanel4 = new widgets.panel.AdaptivePanel();
        senderInfoPanel8 = new widgets.panel.AdaptivePanel();
        senderImagePanel4 = new widgets.panel.AdaptivePanel();
        senderInfoPanel9 = new widgets.panel.AdaptivePanel();
        senderNameLabel4 = new widgets.label.AdaptiveLabel();
        timeLabel4 = new widgets.label.AdaptiveLabel();
        senderTextPanel4 = new widgets.panel.AdaptivePanel();
        adaptiveLabel7 = new widgets.label.AdaptiveLabel();
        adaptiveLabel8 = new widgets.label.AdaptiveLabel();
        sendPanel = new widgets.panel.AdaptivePanel();
        sendTextPanel = new widgets.panel.AdaptivePanel();
        adaptiveTextField1 = new widgets.textfield.AdaptiveTextField();
        virtualKeyboardPanel = new widgets.panel.AdaptivePanel();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        adaptiveButton1 = new widgets.button.AdaptiveButton();
        adaptiveButton2 = new widgets.button.AdaptiveButton();
        adaptiveButton10 = new widgets.button.AdaptiveButton();
        adaptiveButton9 = new widgets.button.AdaptiveButton();
        adaptiveButton8 = new widgets.button.AdaptiveButton();
        adaptiveButton7 = new widgets.button.AdaptiveButton();
        adaptiveButton6 = new widgets.button.AdaptiveButton();
        adaptiveButton5 = new widgets.button.AdaptiveButton();
        adaptiveButton4 = new widgets.button.AdaptiveButton();
        adaptiveButton3 = new widgets.button.AdaptiveButton();
        adaptivePanel3 = new widgets.panel.AdaptivePanel();
        adaptiveButton11 = new widgets.button.AdaptiveButton();
        adaptiveButton12 = new widgets.button.AdaptiveButton();
        adaptiveButton13 = new widgets.button.AdaptiveButton();
        adaptiveButton14 = new widgets.button.AdaptiveButton();
        adaptiveButton15 = new widgets.button.AdaptiveButton();
        adaptiveButton16 = new widgets.button.AdaptiveButton();
        adaptiveButton17 = new widgets.button.AdaptiveButton();
        adaptiveButton18 = new widgets.button.AdaptiveButton();
        adaptiveButton19 = new widgets.button.AdaptiveButton();
        adaptivePanel4 = new widgets.panel.AdaptivePanel();
        adaptiveButton20 = new widgets.button.AdaptiveButton();
        adaptiveButton21 = new widgets.button.AdaptiveButton();
        adaptiveButton22 = new widgets.button.AdaptiveButton();
        adaptiveButton23 = new widgets.button.AdaptiveButton();
        adaptiveButton24 = new widgets.button.AdaptiveButton();
        adaptiveButton25 = new widgets.button.AdaptiveButton();
        adaptiveButton26 = new widgets.button.AdaptiveButton();
        adaptiveButton27 = new widgets.button.AdaptiveButton();
        adaptiveButton31 = new widgets.button.AdaptiveButton();
        adaptivePanel5 = new widgets.panel.AdaptivePanel();
        adaptiveButton28 = new widgets.button.AdaptiveButton();
        adaptiveButton29 = new widgets.button.AdaptiveButton();
        adaptiveButton30 = new widgets.button.AdaptiveButton();

        setLayout(new java.awt.BorderLayout(0, 10));

        contactPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        contactPanel.setMinimumSize(new java.awt.Dimension(125, 100));
        contactPanel.setLayout(new java.awt.BorderLayout());

        adaptivePanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 0));

        avatarPanel.setFunction("marigiannaImg");
        avatarPanel.setName("Panel.Content.MarigiannaImage"); // NOI18N
        adaptivePanel6.add(avatarPanel);

        statusPanel.setLayout(new java.awt.BorderLayout());

        adaptivePanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        statusAvatarPanel.setFunction("StatusAvailableImg");
        statusAvatarPanel.setName("ContactPanel.StatusAvailablePanel"); // NOI18N
        statusAvatarPanel.setLayout(new javax.swing.BoxLayout(statusAvatarPanel, javax.swing.BoxLayout.LINE_AXIS));
        adaptivePanel1.add(statusAvatarPanel);

        adaptiveButton32.setText("Επιλογές");
        adaptiveButton32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton32ActionPerformed(evt);
            }
        });
        adaptivePanel1.add(adaptiveButton32);

        statusPanel.add(adaptivePanel1, java.awt.BorderLayout.NORTH);

        nameLabel.setText("Marigianna Skouradakh: Pame xoro?");
        statusPanel.add(nameLabel, java.awt.BorderLayout.SOUTH);

        adaptivePanel6.add(statusPanel);

        contactPanel.add(adaptivePanel6, java.awt.BorderLayout.NORTH);

        chatButtonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 0));

        videoCallButton.setFunction("ChatButton");
        videoCallButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoCallButtonActionPerformed(evt);
            }
        });
        chatButtonsPanel.add(videoCallButton);

        callButton.setFunction("ChatButton");
        callButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callButtonActionPerformed(evt);
            }
        });
        chatButtonsPanel.add(callButton);

        addButton.setFunction("ChatButton");
        chatButtonsPanel.add(addButton);

        closeButton.setFunction("ChatButton");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        chatButtonsPanel.add(closeButton);

        contactPanel.add(chatButtonsPanel, java.awt.BorderLayout.CENTER);

        add(contactPanel, java.awt.BorderLayout.NORTH);

        receivePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        receivePanel.setLayout(new javax.swing.BoxLayout(receivePanel, javax.swing.BoxLayout.LINE_AXIS));

        scroolContentPanel.setLayout(new java.awt.GridLayout(5, 1, 0, 20));

        conversationKoutsopPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        conversationKoutsopPanel.setLayout(new javax.swing.BoxLayout(conversationKoutsopPanel, javax.swing.BoxLayout.LINE_AXIS));

        senderPanel2.setName("Panel.ChatBox"); // NOI18N
        senderPanel2.setLayout(new java.awt.BorderLayout());

        northPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 10));

        senderInfoPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        senderImagePanel1.setFunction("koutsopImg");
        senderImagePanel1.setMaximumSize(new java.awt.Dimension(50, 50));
        senderImagePanel1.setMinimumSize(new java.awt.Dimension(50, 50));
        senderImagePanel1.setName("Panel.Content.KoutsopImage"); // NOI18N
        senderImagePanel1.setPreferredSize(new java.awt.Dimension(50, 50));
        senderImagePanel1.setLayout(new javax.swing.BoxLayout(senderImagePanel1, javax.swing.BoxLayout.LINE_AXIS));
        senderInfoPanel2.add(senderImagePanel1);

        senderInfoPanel3.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        senderNameLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        senderNameLabel1.setText("Koutsop:");
        senderInfoPanel3.add(senderNameLabel1);

        timeLabel1.setText("Sent at 12:03 PM on Sunday");
        senderInfoPanel3.add(timeLabel1);

        senderInfoPanel2.add(senderInfoPanel3);

        northPanel1.add(senderInfoPanel2);

        senderPanel2.add(northPanel1, java.awt.BorderLayout.NORTH);

        senderTextPanel1.setLayout(new javax.swing.BoxLayout(senderTextPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        adaptiveLabel3.setText("Pws paei eisai kala? Elpizw na eisai kala. Ta leme");
        senderTextPanel1.add(adaptiveLabel3);

        senderPanel2.add(senderTextPanel1, java.awt.BorderLayout.CENTER);

        conversationKoutsopPanel.add(senderPanel2);

        scroolContentPanel.add(conversationKoutsopPanel);

        conversationMarigiannaPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        conversationMarigiannaPanel.setLayout(new javax.swing.BoxLayout(conversationMarigiannaPanel, javax.swing.BoxLayout.LINE_AXIS));

        senderPanel1.setName("Panel.ChatBox"); // NOI18N
        senderPanel1.setLayout(new java.awt.BorderLayout());

        northPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 10));

        senderInfoPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        senderImagePanel.setFunction("marigiannaImg");
        senderImagePanel.setMaximumSize(new java.awt.Dimension(50, 50));
        senderImagePanel.setMinimumSize(new java.awt.Dimension(50, 50));
        senderImagePanel.setName("Panel.Content.MarigiannaImage"); // NOI18N
        senderImagePanel.setPreferredSize(new java.awt.Dimension(50, 50));
        senderImagePanel.setLayout(new javax.swing.BoxLayout(senderImagePanel, javax.swing.BoxLayout.LINE_AXIS));
        senderInfoPanel1.add(senderImagePanel);

        senderInfoPanel.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        senderNameLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        senderNameLabel.setText("Marigianna:");
        senderInfoPanel.add(senderNameLabel);

        timeLabel.setText("Sent at 12:03 PM on Sunday");
        senderInfoPanel.add(timeLabel);

        senderInfoPanel1.add(senderInfoPanel);

        northPanel.add(senderInfoPanel1);

        senderPanel1.add(northPanel, java.awt.BorderLayout.NORTH);

        senderTextPanel.setLayout(new javax.swing.BoxLayout(senderTextPanel, javax.swing.BoxLayout.PAGE_AXIS));

        adaptiveLabel2.setText("Bariemai thn zwh mou n to 3reis auto laalalalal");
        senderTextPanel.add(adaptiveLabel2);

        adaptiveLabel1.setText("Bariemai thn zwh mou n to 3reis auto");
        senderTextPanel.add(adaptiveLabel1);

        senderPanel1.add(senderTextPanel, java.awt.BorderLayout.CENTER);

        conversationMarigiannaPanel.add(senderPanel1);

        scroolContentPanel.add(conversationMarigiannaPanel);

        conversationKoutsopPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        conversationKoutsopPanel1.setLayout(new javax.swing.BoxLayout(conversationKoutsopPanel1, javax.swing.BoxLayout.LINE_AXIS));

        senderPanel3.setName("Panel.ChatBox"); // NOI18N
        senderPanel3.setLayout(new java.awt.BorderLayout());

        northPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 10));

        senderInfoPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        senderImagePanel2.setFunction("koutsopImg");
        senderImagePanel2.setMaximumSize(new java.awt.Dimension(50, 50));
        senderImagePanel2.setMinimumSize(new java.awt.Dimension(50, 50));
        senderImagePanel2.setName("Panel.Content.KoutsopImage"); // NOI18N
        senderImagePanel2.setPreferredSize(new java.awt.Dimension(50, 50));
        senderImagePanel2.setLayout(new javax.swing.BoxLayout(senderImagePanel2, javax.swing.BoxLayout.LINE_AXIS));
        senderInfoPanel4.add(senderImagePanel2);

        senderInfoPanel5.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        senderNameLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        senderNameLabel2.setText("Koutsop:");
        senderInfoPanel5.add(senderNameLabel2);

        timeLabel2.setText("Sent at 12:03 PM on Sunday");
        senderInfoPanel5.add(timeLabel2);

        senderInfoPanel4.add(senderInfoPanel5);

        northPanel2.add(senderInfoPanel4);

        senderPanel3.add(northPanel2, java.awt.BorderLayout.NORTH);

        senderTextPanel2.setLayout(new javax.swing.BoxLayout(senderTextPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        adaptiveLabel4.setText("Pws paei eisai kala? Elpizw na eisai kala. Ta leme");
        senderTextPanel2.add(adaptiveLabel4);

        senderPanel3.add(senderTextPanel2, java.awt.BorderLayout.CENTER);

        conversationKoutsopPanel1.add(senderPanel3);

        scroolContentPanel.add(conversationKoutsopPanel1);

        conversationMarigiannaPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        conversationMarigiannaPanel1.setLayout(new javax.swing.BoxLayout(conversationMarigiannaPanel1, javax.swing.BoxLayout.LINE_AXIS));

        senderPanel4.setName("Panel.ChatBox"); // NOI18N
        senderPanel4.setLayout(new java.awt.BorderLayout());

        northPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 10));

        senderInfoPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        senderImagePanel3.setFunction("marigiannaImg");
        senderImagePanel3.setMaximumSize(new java.awt.Dimension(50, 50));
        senderImagePanel3.setMinimumSize(new java.awt.Dimension(50, 50));
        senderImagePanel3.setName("Panel.Content.MarigiannaImage"); // NOI18N
        senderImagePanel3.setPreferredSize(new java.awt.Dimension(50, 50));
        senderImagePanel3.setLayout(new javax.swing.BoxLayout(senderImagePanel3, javax.swing.BoxLayout.LINE_AXIS));
        senderInfoPanel6.add(senderImagePanel3);

        senderInfoPanel7.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        senderNameLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        senderNameLabel3.setText("Marigianna:");
        senderInfoPanel7.add(senderNameLabel3);

        timeLabel3.setText("Sent at 12:03 PM on Sunday");
        senderInfoPanel7.add(timeLabel3);

        senderInfoPanel6.add(senderInfoPanel7);

        northPanel3.add(senderInfoPanel6);

        senderPanel4.add(northPanel3, java.awt.BorderLayout.NORTH);

        senderTextPanel3.setLayout(new javax.swing.BoxLayout(senderTextPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        adaptiveLabel5.setText("Bariemai thn zwh mou n to 3reis auto laalalalal");
        senderTextPanel3.add(adaptiveLabel5);

        adaptiveLabel6.setText("Bariemai thn zwh mou n to 3reis auto");
        senderTextPanel3.add(adaptiveLabel6);

        senderPanel4.add(senderTextPanel3, java.awt.BorderLayout.CENTER);

        conversationMarigiannaPanel1.add(senderPanel4);

        scroolContentPanel.add(conversationMarigiannaPanel1);

        conversationMarigiannaPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 3, true));
        conversationMarigiannaPanel2.setLayout(new javax.swing.BoxLayout(conversationMarigiannaPanel2, javax.swing.BoxLayout.LINE_AXIS));

        senderPanel5.setName("Panel.ChatBox"); // NOI18N
        senderPanel5.setLayout(new java.awt.BorderLayout());

        northPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 10));

        senderInfoPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        senderImagePanel4.setFunction("marigiannaImg");
        senderImagePanel4.setMaximumSize(new java.awt.Dimension(50, 50));
        senderImagePanel4.setMinimumSize(new java.awt.Dimension(50, 50));
        senderImagePanel4.setName("Panel.Content.MarigiannaImage"); // NOI18N
        senderImagePanel4.setPreferredSize(new java.awt.Dimension(50, 50));
        senderImagePanel4.setLayout(new javax.swing.BoxLayout(senderImagePanel4, javax.swing.BoxLayout.LINE_AXIS));
        senderInfoPanel8.add(senderImagePanel4);

        senderInfoPanel9.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        senderNameLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        senderNameLabel4.setText("Marigianna:");
        senderInfoPanel9.add(senderNameLabel4);

        timeLabel4.setText("Sent at 12:03 PM on Sunday");
        senderInfoPanel9.add(timeLabel4);

        senderInfoPanel8.add(senderInfoPanel9);

        northPanel4.add(senderInfoPanel8);

        senderPanel5.add(northPanel4, java.awt.BorderLayout.NORTH);

        senderTextPanel4.setLayout(new javax.swing.BoxLayout(senderTextPanel4, javax.swing.BoxLayout.PAGE_AXIS));

        adaptiveLabel7.setText("Bariemai thn zwh mou n to 3reis auto laalalalal");
        senderTextPanel4.add(adaptiveLabel7);

        adaptiveLabel8.setText("Bariemai thn zwh mou n to 3reis auto");
        senderTextPanel4.add(adaptiveLabel8);

        senderPanel5.add(senderTextPanel4, java.awt.BorderLayout.CENTER);

        conversationMarigiannaPanel2.add(senderPanel5);

        scroolContentPanel.add(conversationMarigiannaPanel2);

        jScrollPane2.setViewportView(scroolContentPanel);

        receivePanel.add(jScrollPane2);

        add(receivePanel, java.awt.BorderLayout.CENTER);

        sendPanel.setLayout(new java.awt.BorderLayout(0, 5));

        sendTextPanel.setLayout(new javax.swing.BoxLayout(sendTextPanel, javax.swing.BoxLayout.LINE_AXIS));
        sendTextPanel.add(adaptiveTextField1);

        sendPanel.add(sendTextPanel, java.awt.BorderLayout.NORTH);

        virtualKeyboardPanel.setLayout(new java.awt.GridLayout(4, 1));

        adaptiveButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton1.setText("Q");
        adaptivePanel2.add(adaptiveButton1);

        adaptiveButton2.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton2.setText("W");
        adaptivePanel2.add(adaptiveButton2);

        adaptiveButton10.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton10.setText("E");
        adaptivePanel2.add(adaptiveButton10);

        adaptiveButton9.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton9.setText("R");
        adaptivePanel2.add(adaptiveButton9);

        adaptiveButton8.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton8.setText("T");
        adaptivePanel2.add(adaptiveButton8);

        adaptiveButton7.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton7.setText("Y");
        adaptivePanel2.add(adaptiveButton7);

        adaptiveButton6.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton6.setText("U");
        adaptivePanel2.add(adaptiveButton6);

        adaptiveButton5.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton5.setText("I");
        adaptivePanel2.add(adaptiveButton5);

        adaptiveButton4.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton4.setText("O");
        adaptivePanel2.add(adaptiveButton4);

        adaptiveButton3.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton3.setText("P");
        adaptivePanel2.add(adaptiveButton3);

        virtualKeyboardPanel.add(adaptivePanel2);

        adaptiveButton11.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton11.setText("A");
        adaptivePanel3.add(adaptiveButton11);

        adaptiveButton12.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton12.setText("S");
        adaptivePanel3.add(adaptiveButton12);

        adaptiveButton13.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton13.setText("D");
        adaptivePanel3.add(adaptiveButton13);

        adaptiveButton14.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton14.setText("F");
        adaptivePanel3.add(adaptiveButton14);

        adaptiveButton15.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton15.setText("G");
        adaptivePanel3.add(adaptiveButton15);

        adaptiveButton16.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton16.setText("H");
        adaptivePanel3.add(adaptiveButton16);

        adaptiveButton17.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton17.setText("J");
        adaptivePanel3.add(adaptiveButton17);

        adaptiveButton18.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton18.setText("K");
        adaptivePanel3.add(adaptiveButton18);

        adaptiveButton19.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton19.setText("L");
        adaptivePanel3.add(adaptiveButton19);

        virtualKeyboardPanel.add(adaptivePanel3);

        adaptivePanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 7, 5));

        adaptiveButton20.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptivePanel4.add(adaptiveButton20);

        adaptiveButton21.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton21.setText("z");
        adaptivePanel4.add(adaptiveButton21);

        adaptiveButton22.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton22.setText("x");
        adaptivePanel4.add(adaptiveButton22);

        adaptiveButton23.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton23.setText("c");
        adaptivePanel4.add(adaptiveButton23);

        adaptiveButton24.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton24.setText("v");
        adaptivePanel4.add(adaptiveButton24);

        adaptiveButton25.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton25.setText("b");
        adaptivePanel4.add(adaptiveButton25);

        adaptiveButton26.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton26.setText("n");
        adaptivePanel4.add(adaptiveButton26);

        adaptiveButton27.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton27.setText("m");
        adaptivePanel4.add(adaptiveButton27);

        adaptiveButton31.setMargin(new java.awt.Insets(0, 0, 0, 0));
        adaptiveButton31.setText("del");
        adaptivePanel4.add(adaptiveButton31);

        virtualKeyboardPanel.add(adaptivePanel4);

        adaptivePanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 4, 4, 4));
        adaptivePanel5.setLayout(new java.awt.BorderLayout(15, 0));

        adaptiveButton28.setText(".?123");
        adaptivePanel5.add(adaptiveButton28, java.awt.BorderLayout.WEST);

        adaptiveButton29.setText("SPACE");
        adaptivePanel5.add(adaptiveButton29, java.awt.BorderLayout.CENTER);

        adaptiveButton30.setText("return");
        adaptivePanel5.add(adaptiveButton30, java.awt.BorderLayout.EAST);

        virtualKeyboardPanel.add(adaptivePanel5);

        sendPanel.add(virtualKeyboardPanel, java.awt.BorderLayout.CENTER);

        add(sendPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

	private void adaptiveButton32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton32ActionPerformed
		SetPreferencesButtonsVisibility(isVisible = !isVisible);
	}//GEN-LAST:event_adaptiveButton32ActionPerformed

	private void videoCallButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoCallButtonActionPerformed
		MainWindowPDA.showPanel(new VideoCall());
	}//GEN-LAST:event_videoCallButtonActionPerformed

	private void callButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callButtonActionPerformed
		MainWindowPDA.showPanel(new Call());
	}//GEN-LAST:event_callButtonActionPerformed

	private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
		MainWindowPDA.showPanel(new PDAMainView());
	}//GEN-LAST:event_closeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.AdaptiveButton adaptiveButton1;
    private widgets.button.AdaptiveButton adaptiveButton10;
    private widgets.button.AdaptiveButton adaptiveButton11;
    private widgets.button.AdaptiveButton adaptiveButton12;
    private widgets.button.AdaptiveButton adaptiveButton13;
    private widgets.button.AdaptiveButton adaptiveButton14;
    private widgets.button.AdaptiveButton adaptiveButton15;
    private widgets.button.AdaptiveButton adaptiveButton16;
    private widgets.button.AdaptiveButton adaptiveButton17;
    private widgets.button.AdaptiveButton adaptiveButton18;
    private widgets.button.AdaptiveButton adaptiveButton19;
    private widgets.button.AdaptiveButton adaptiveButton2;
    private widgets.button.AdaptiveButton adaptiveButton20;
    private widgets.button.AdaptiveButton adaptiveButton21;
    private widgets.button.AdaptiveButton adaptiveButton22;
    private widgets.button.AdaptiveButton adaptiveButton23;
    private widgets.button.AdaptiveButton adaptiveButton24;
    private widgets.button.AdaptiveButton adaptiveButton25;
    private widgets.button.AdaptiveButton adaptiveButton26;
    private widgets.button.AdaptiveButton adaptiveButton27;
    private widgets.button.AdaptiveButton adaptiveButton28;
    private widgets.button.AdaptiveButton adaptiveButton29;
    private widgets.button.AdaptiveButton adaptiveButton3;
    private widgets.button.AdaptiveButton adaptiveButton30;
    private widgets.button.AdaptiveButton adaptiveButton31;
    private widgets.button.AdaptiveButton adaptiveButton32;
    private widgets.button.AdaptiveButton adaptiveButton4;
    private widgets.button.AdaptiveButton adaptiveButton5;
    private widgets.button.AdaptiveButton adaptiveButton6;
    private widgets.button.AdaptiveButton adaptiveButton7;
    private widgets.button.AdaptiveButton adaptiveButton8;
    private widgets.button.AdaptiveButton adaptiveButton9;
    private widgets.label.AdaptiveLabel adaptiveLabel1;
    private widgets.label.AdaptiveLabel adaptiveLabel2;
    private widgets.label.AdaptiveLabel adaptiveLabel3;
    private widgets.label.AdaptiveLabel adaptiveLabel4;
    private widgets.label.AdaptiveLabel adaptiveLabel5;
    private widgets.label.AdaptiveLabel adaptiveLabel6;
    private widgets.label.AdaptiveLabel adaptiveLabel7;
    private widgets.label.AdaptiveLabel adaptiveLabel8;
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.panel.AdaptivePanel adaptivePanel3;
    private widgets.panel.AdaptivePanel adaptivePanel4;
    private widgets.panel.AdaptivePanel adaptivePanel5;
    private widgets.panel.AdaptivePanel adaptivePanel6;
    private widgets.textfield.AdaptiveTextField adaptiveTextField1;
    private widgets.button.AdaptiveButton addButton;
    private widgets.panel.AdaptivePanel avatarPanel;
    private widgets.button.AdaptiveButton callButton;
    private widgets.panel.AdaptivePanel chatButtonsPanel;
    private widgets.button.AdaptiveButton closeButton;
    private widgets.panel.AdaptivePanel contactPanel;
    private widgets.panel.AdaptivePanel conversationKoutsopPanel;
    private widgets.panel.AdaptivePanel conversationKoutsopPanel1;
    private widgets.panel.AdaptivePanel conversationMarigiannaPanel;
    private widgets.panel.AdaptivePanel conversationMarigiannaPanel1;
    private widgets.panel.AdaptivePanel conversationMarigiannaPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private widgets.label.AdaptiveLabel nameLabel;
    private widgets.panel.AdaptivePanel northPanel;
    private widgets.panel.AdaptivePanel northPanel1;
    private widgets.panel.AdaptivePanel northPanel2;
    private widgets.panel.AdaptivePanel northPanel3;
    private widgets.panel.AdaptivePanel northPanel4;
    private widgets.panel.AdaptivePanel receivePanel;
    private widgets.panel.AdaptivePanel scroolContentPanel;
    private widgets.panel.AdaptivePanel sendPanel;
    private widgets.panel.AdaptivePanel sendTextPanel;
    private widgets.panel.AdaptivePanel senderImagePanel;
    private widgets.panel.AdaptivePanel senderImagePanel1;
    private widgets.panel.AdaptivePanel senderImagePanel2;
    private widgets.panel.AdaptivePanel senderImagePanel3;
    private widgets.panel.AdaptivePanel senderImagePanel4;
    private widgets.panel.AdaptivePanel senderInfoPanel;
    private widgets.panel.AdaptivePanel senderInfoPanel1;
    private widgets.panel.AdaptivePanel senderInfoPanel2;
    private widgets.panel.AdaptivePanel senderInfoPanel3;
    private widgets.panel.AdaptivePanel senderInfoPanel4;
    private widgets.panel.AdaptivePanel senderInfoPanel5;
    private widgets.panel.AdaptivePanel senderInfoPanel6;
    private widgets.panel.AdaptivePanel senderInfoPanel7;
    private widgets.panel.AdaptivePanel senderInfoPanel8;
    private widgets.panel.AdaptivePanel senderInfoPanel9;
    private widgets.label.AdaptiveLabel senderNameLabel;
    private widgets.label.AdaptiveLabel senderNameLabel1;
    private widgets.label.AdaptiveLabel senderNameLabel2;
    private widgets.label.AdaptiveLabel senderNameLabel3;
    private widgets.label.AdaptiveLabel senderNameLabel4;
    private widgets.panel.AdaptivePanel senderPanel1;
    private widgets.panel.AdaptivePanel senderPanel2;
    private widgets.panel.AdaptivePanel senderPanel3;
    private widgets.panel.AdaptivePanel senderPanel4;
    private widgets.panel.AdaptivePanel senderPanel5;
    private widgets.panel.AdaptivePanel senderTextPanel;
    private widgets.panel.AdaptivePanel senderTextPanel1;
    private widgets.panel.AdaptivePanel senderTextPanel2;
    private widgets.panel.AdaptivePanel senderTextPanel3;
    private widgets.panel.AdaptivePanel senderTextPanel4;
    private widgets.panel.AdaptivePanel statusAvatarPanel;
    private widgets.panel.AdaptivePanel statusPanel;
    private widgets.label.AdaptiveLabel timeLabel;
    private widgets.label.AdaptiveLabel timeLabel1;
    private widgets.label.AdaptiveLabel timeLabel2;
    private widgets.label.AdaptiveLabel timeLabel3;
    private widgets.label.AdaptiveLabel timeLabel4;
    private widgets.button.AdaptiveButton videoCallButton;
    private widgets.panel.AdaptivePanel virtualKeyboardPanel;
    // End of variables declaration//GEN-END:variables
}
