/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PDAMainView.java
 *
 * Created on 1 Δεκ 2011, 3:52:26 μμ
 */
package assignment2.pda;

import javax.swing.ImageIcon;
import pda.MainWindowPDA;
import utilities.Adaptation;
import utilities.DMSLConnector;

/**
 *
 * @author koutsop
 */
public class PDAMainView extends javax.swing.JPanel {
	private boolean border = false;
	/** Creates new form PDAMainView */
	public PDAMainView() {
		initComponents();
        Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
		
        String path = DMSLConnector.getInstance().getClient(false).Evaluate("AddButton");
        addContactButton.setIcon(new ImageIcon(getClass().getResource(path)));  
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("GroupButton");
        groupContactsButton.setIcon(new ImageIcon(getClass().getResource(path)));  
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("SearchButton");
        searchButton.setIcon(new ImageIcon(getClass().getResource(path))); 
        
        path = DMSLConnector.getInstance().getClient(false).Evaluate("RemoveButton");
        removeContactButton.setIcon(new ImageIcon(getClass().getResource(path)));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonsPanel = new widgets.panel.AdaptivePanel();
        menuButtonsPanels = new widgets.panel.AdaptivePanel();
        profileButton = new widgets.button.MainMenuButton();
        settingsButton = new widgets.button.MainMenuButton();
        hellpButton = new widgets.button.MainMenuButton();
        contactsButtonsPanel = new widgets.panel.AdaptivePanel();
        addContactButton = new widgets.button.AdaptiveButton();
        removeContactButton = new widgets.button.AdaptiveButton();
        groupContactsButton = new widgets.button.AdaptiveButton();
        searchPanel = new widgets.panel.AdaptivePanel();
        adaptiveTextField1 = new widgets.textfield.AdaptiveTextField();
        searchButton = new widgets.button.AdaptiveButton();
        contacstListPanel = new widgets.panel.AdaptivePanel();
        contentsPanel = new widgets.panel.AdaptivePanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        adaptivePanel1 = new widgets.panel.AdaptivePanel();
        adaptiveButton2 = new widgets.button.AdaptiveButton();
        adaptiveButton3 = new widgets.button.AdaptiveButton();
        adaptiveButton4 = new widgets.button.AdaptiveButton();
        adaptiveButton5 = new widgets.button.AdaptiveButton();
        adaptiveButton6 = new widgets.button.AdaptiveButton();
        adaptiveButton7 = new widgets.button.AdaptiveButton();
        adaptiveButton8 = new widgets.button.AdaptiveButton();
        adaptiveButton9 = new widgets.button.AdaptiveButton();
        adaptiveButton10 = new widgets.button.AdaptiveButton();
        adaptiveButton11 = new widgets.button.AdaptiveButton();
        adaptiveButton12 = new widgets.button.AdaptiveButton();
        adaptiveButton13 = new widgets.button.AdaptiveButton();
        adaptiveButton14 = new widgets.button.AdaptiveButton();
        adaptiveButton15 = new widgets.button.AdaptiveButton();
        adaptiveButton16 = new widgets.button.AdaptiveButton();
        adaptiveButton17 = new widgets.button.AdaptiveButton();
        adaptiveButton18 = new widgets.button.AdaptiveButton();
        adaptiveButton19 = new widgets.button.AdaptiveButton();
        adaptiveButton20 = new widgets.button.AdaptiveButton();
        adaptiveButton21 = new widgets.button.AdaptiveButton();
        adaptiveButton22 = new widgets.button.AdaptiveButton();
        adaptiveButton23 = new widgets.button.AdaptiveButton();
        adaptiveButton24 = new widgets.button.AdaptiveButton();
        adaptiveButton25 = new widgets.button.AdaptiveButton();

        setLayout(new java.awt.BorderLayout(0, 5));

        buttonsPanel.setLayout(new javax.swing.BoxLayout(buttonsPanel, javax.swing.BoxLayout.PAGE_AXIS));

        menuButtonsPanels.setLayout(new java.awt.GridLayout(1, 3));

        profileButton.setText("Profile");
        profileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileButtonActionPerformed(evt);
            }
        });
        menuButtonsPanels.add(profileButton);

        settingsButton.setText("Settings");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        menuButtonsPanels.add(settingsButton);

        hellpButton.setText("Help");
        hellpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hellpButtonActionPerformed(evt);
            }
        });
        menuButtonsPanels.add(hellpButton);

        buttonsPanel.add(menuButtonsPanels);

        contactsButtonsPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        addContactButton.setFunction("ContactsActionButton");
        addContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addContactButtonActionPerformed(evt);
            }
        });
        contactsButtonsPanel.add(addContactButton);

        removeContactButton.setFunction("ContactsActionButton");
        removeContactButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeContactButtonActionPerformed(evt);
            }
        });
        contactsButtonsPanel.add(removeContactButton);

        groupContactsButton.setFunction("ContactsActionButton");
        groupContactsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                groupContactsButtonActionPerformed(evt);
            }
        });
        contactsButtonsPanel.add(groupContactsButton);

        buttonsPanel.add(contactsButtonsPanel);

        searchPanel.setLayout(new java.awt.BorderLayout(10, 0));

        adaptiveTextField1.setText("adaptiveTextField1");
        searchPanel.add(adaptiveTextField1, java.awt.BorderLayout.CENTER);

        searchButton.setFunction("ContactsActionButton");
        searchPanel.add(searchButton, java.awt.BorderLayout.EAST);

        buttonsPanel.add(searchPanel);

        add(buttonsPanel, java.awt.BorderLayout.NORTH);

        contacstListPanel.setLayout(new javax.swing.BoxLayout(contacstListPanel, javax.swing.BoxLayout.LINE_AXIS));

        contentsPanel.setLayout(new javax.swing.BoxLayout(contentsPanel, javax.swing.BoxLayout.LINE_AXIS));

        adaptivePanel1.setLayout(new javax.swing.BoxLayout(adaptivePanel1, javax.swing.BoxLayout.PAGE_AXIS));

        adaptiveButton2.setText("adaptiveButton2");
        adaptivePanel1.add(adaptiveButton2);

        adaptiveButton3.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton3);

        adaptiveButton4.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton4);

        adaptiveButton5.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton5);

        adaptiveButton6.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton6);

        adaptiveButton7.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton7);

        adaptiveButton8.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton8);

        adaptiveButton9.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton9);

        adaptiveButton10.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton10);

        adaptiveButton11.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton11);

        adaptiveButton12.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton12);

        adaptiveButton13.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton13);

        adaptiveButton14.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton14);

        adaptiveButton15.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton15);

        adaptiveButton16.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton16);

        adaptiveButton17.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton17);

        adaptiveButton18.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton18);

        adaptiveButton19.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton19);

        adaptiveButton20.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton20);

        adaptiveButton21.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton21);

        adaptiveButton22.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton22);

        adaptiveButton23.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton23);

        adaptiveButton24.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton24);

        adaptiveButton25.setText("adaptiveButton3");
        adaptivePanel1.add(adaptiveButton25);

        jScrollPane1.setViewportView(adaptivePanel1);

        contentsPanel.add(jScrollPane1);

        contacstListPanel.add(contentsPanel);

        add(contacstListPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

	private void addContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addContactButtonActionPerformed
		MainWindowPDA.showPanel(new SearchForNewContact());
	}//GEN-LAST:event_addContactButtonActionPerformed

	private void removeContactButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeContactButtonActionPerformed
		MainWindowPDA.showPanel(new DeleteContact());
	}//GEN-LAST:event_removeContactButtonActionPerformed

	private void groupContactsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_groupContactsButtonActionPerformed
		
	}//GEN-LAST:event_groupContactsButtonActionPerformed

	private void hellpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hellpButtonActionPerformed
		MainWindowPDA.showPanel(new Help());
	}//GEN-LAST:event_hellpButtonActionPerformed

	private void profileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileButtonActionPerformed
		MainWindowPDA.showPanel(new Profile());
	}//GEN-LAST:event_profileButtonActionPerformed

	private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
		MainWindowPDA.showPanel(new SettingsMainView());
	}//GEN-LAST:event_settingsButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.AdaptiveButton adaptiveButton10;
    private widgets.button.AdaptiveButton adaptiveButton11;
    private widgets.button.AdaptiveButton adaptiveButton12;
    private widgets.button.AdaptiveButton adaptiveButton13;
    private widgets.button.AdaptiveButton adaptiveButton14;
    private widgets.button.AdaptiveButton adaptiveButton15;
    private widgets.button.AdaptiveButton adaptiveButton16;
    private widgets.button.AdaptiveButton adaptiveButton17;
    private widgets.button.AdaptiveButton adaptiveButton18;
    private widgets.button.AdaptiveButton adaptiveButton19;
    private widgets.button.AdaptiveButton adaptiveButton2;
    private widgets.button.AdaptiveButton adaptiveButton20;
    private widgets.button.AdaptiveButton adaptiveButton21;
    private widgets.button.AdaptiveButton adaptiveButton22;
    private widgets.button.AdaptiveButton adaptiveButton23;
    private widgets.button.AdaptiveButton adaptiveButton24;
    private widgets.button.AdaptiveButton adaptiveButton25;
    private widgets.button.AdaptiveButton adaptiveButton3;
    private widgets.button.AdaptiveButton adaptiveButton4;
    private widgets.button.AdaptiveButton adaptiveButton5;
    private widgets.button.AdaptiveButton adaptiveButton6;
    private widgets.button.AdaptiveButton adaptiveButton7;
    private widgets.button.AdaptiveButton adaptiveButton8;
    private widgets.button.AdaptiveButton adaptiveButton9;
    private widgets.panel.AdaptivePanel adaptivePanel1;
    private widgets.textfield.AdaptiveTextField adaptiveTextField1;
    private widgets.button.AdaptiveButton addContactButton;
    private widgets.panel.AdaptivePanel buttonsPanel;
    private widgets.panel.AdaptivePanel contacstListPanel;
    private widgets.panel.AdaptivePanel contactsButtonsPanel;
    private widgets.panel.AdaptivePanel contentsPanel;
    private widgets.button.AdaptiveButton groupContactsButton;
    private widgets.button.MainMenuButton hellpButton;
    private javax.swing.JScrollPane jScrollPane1;
    private widgets.panel.AdaptivePanel menuButtonsPanels;
    private widgets.button.MainMenuButton profileButton;
    private widgets.button.AdaptiveButton removeContactButton;
    private widgets.button.AdaptiveButton searchButton;
    private widgets.panel.AdaptivePanel searchPanel;
    private widgets.button.MainMenuButton settingsButton;
    // End of variables declaration//GEN-END:variables
}
