/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NoDisabilitySettingsView.java
 *
 * Created on Nov 24, 2011, 8:03:00 PM
 */
package assignment2.NoDisability;

import assignment2.AdaptableSettingsView;
import assignment2.Chat;
import pc.MainWindowPC;
import utilities.Adaptation;

/**
 *
 * @author Marigianna
 */
public class NoDisabilitySettingsView extends javax.swing.JPanel {

    /** Creates new form NoDisabilitySettingsView */
    public NoDisabilitySettingsView() {
        initComponents();
         Adaptation.automaticallySetRuntime(this);
        Adaptation.automaticallyAdapt(this);
		//this.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menuPanel = new widgets.panel.AdaptivePanel();
        maniMenuPanel = new widgets.panel.AdaptivePanel();
        adaptiveButton1 = new widgets.button.AdaptiveButton();
        adaptiveButton2 = new widgets.button.AdaptiveButton();
        adaptiveButton3 = new widgets.button.AdaptiveButton();
        settingsButton = new widgets.button.AdaptiveButton();
        spacePanel = new widgets.panel.AdaptivePanel();
        tabbedPanel = new widgets.panel.AdaptivePanel();
        generalButton = new widgets.button.MainMenuButton();
        historyButton = new widgets.button.MainMenuButton();
        blockedButton = new widgets.button.MainMenuButton();
        notificationsButton = new widgets.button.MainMenuButton();
        appearanceButton = new widgets.button.MainMenuButton();
        contentPanel = new widgets.panel.AdaptivePanel();
        bottomPanel = new widgets.panel.AdaptivePanel();
        adaptiveButton4 = new widgets.button.AdaptiveButton();
        adaptivePanel2 = new widgets.panel.AdaptivePanel();
        adaptiveButton5 = new widgets.button.AdaptiveButton();
        adaptiveButton6 = new widgets.button.AdaptiveButton();

        jPanel1.setMaximumSize(new java.awt.Dimension(1000, 688));
        jPanel1.setMinimumSize(new java.awt.Dimension(1000, 688));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 688));
        jPanel1.setLayout(new java.awt.BorderLayout());

        menuPanel.setMaximumSize(new java.awt.Dimension(501, 100));
        menuPanel.setMinimumSize(new java.awt.Dimension(501, 100));
        menuPanel.setPreferredSize(new java.awt.Dimension(501, 100));
        menuPanel.setLayout(new javax.swing.BoxLayout(menuPanel, javax.swing.BoxLayout.PAGE_AXIS));

        maniMenuPanel.setLayout(new javax.swing.BoxLayout(maniMenuPanel, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveButton1.setText("adaptiveButton1");
        maniMenuPanel.add(adaptiveButton1);

        adaptiveButton2.setText("adaptiveButton2");
        maniMenuPanel.add(adaptiveButton2);

        adaptiveButton3.setText("adaptiveButton3");
        maniMenuPanel.add(adaptiveButton3);

        settingsButton.setText("Ρυθμίσεις");
        settingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsButtonActionPerformed(evt);
            }
        });
        maniMenuPanel.add(settingsButton);

        menuPanel.add(maniMenuPanel);

        spacePanel.setPreferredSize(new java.awt.Dimension(1000, 5));

        javax.swing.GroupLayout spacePanelLayout = new javax.swing.GroupLayout(spacePanel);
        spacePanel.setLayout(spacePanelLayout);
        spacePanelLayout.setHorizontalGroup(
            spacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        spacePanelLayout.setVerticalGroup(
            spacePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        menuPanel.add(spacePanel);

        tabbedPanel.setLayout(new javax.swing.BoxLayout(tabbedPanel, javax.swing.BoxLayout.LINE_AXIS));

        generalButton.setText("Γενικά");
        generalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalButtonActionPerformed(evt);
            }
        });
        tabbedPanel.add(generalButton);

        historyButton.setText("Ιστορικό");
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });
        tabbedPanel.add(historyButton);

        blockedButton.setText("Αποκλεισμένοι");
        tabbedPanel.add(blockedButton);

        notificationsButton.setText("Ειδοποιήσεις");
        tabbedPanel.add(notificationsButton);

        appearanceButton.setText("Εμφάνιση");
        tabbedPanel.add(appearanceButton);

        menuPanel.add(tabbedPanel);

        jPanel1.add(menuPanel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(contentPanel, java.awt.BorderLayout.CENTER);

        bottomPanel.setPreferredSize(new java.awt.Dimension(1000, 110));
        bottomPanel.setLayout(new javax.swing.BoxLayout(bottomPanel, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveButton4.setText("Βοήθεια");
        adaptiveButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adaptiveButton4ActionPerformed(evt);
            }
        });
        bottomPanel.add(adaptiveButton4);

        adaptiveButton5.setText("Άκυρο");

        adaptiveButton6.setText("ΟΚ");

        javax.swing.GroupLayout adaptivePanel2Layout = new javax.swing.GroupLayout(adaptivePanel2);
        adaptivePanel2.setLayout(adaptivePanel2Layout);
        adaptivePanel2Layout.setHorizontalGroup(
            adaptivePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adaptivePanel2Layout.createSequentialGroup()
                .addContainerGap(742, Short.MAX_VALUE)
                .addComponent(adaptiveButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adaptiveButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        adaptivePanel2Layout.setVerticalGroup(
            adaptivePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adaptivePanel2Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(adaptivePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adaptiveButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adaptiveButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );

        bottomPanel.add(adaptivePanel2);

        jPanel1.add(bottomPanel, java.awt.BorderLayout.PAGE_END);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

private void settingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsButtonActionPerformed
        AdaptableSettingsView settings = new AdaptableSettingsView();       
        MainWindowPC.showPanel(settings);
}//GEN-LAST:event_settingsButtonActionPerformed

private void adaptiveButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adaptiveButton4ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_adaptiveButton4ActionPerformed

private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
   
}//GEN-LAST:event_historyButtonActionPerformed

private void generalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalButtonActionPerformed
// TODO add your handling code here:
    // Set the appropriate tab as selected
   generalButton.setSelected(true);
   historyButton.setSelected(false);
   appearanceButton.setSelected(false);
   blockedButton.setSelected(false);
   notificationsButton.setSelected(false);
  
   // Instantiate the new screen
   GeneralSettingsPanel generalSettings = new GeneralSettingsPanel();
   generalSettings.setVisible(true);

  // Chat a = new Chat();
   // Remove the contents of the content panel & add the new screen
   contentPanel.removeAll();
   contentPanel.add(generalSettings);
   contentPanel.repaint();
   contentPanel.validate();
}//GEN-LAST:event_generalButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.AdaptiveButton adaptiveButton1;
    private widgets.button.AdaptiveButton adaptiveButton2;
    private widgets.button.AdaptiveButton adaptiveButton3;
    private widgets.button.AdaptiveButton adaptiveButton4;
    private widgets.button.AdaptiveButton adaptiveButton5;
    private widgets.button.AdaptiveButton adaptiveButton6;
    private widgets.panel.AdaptivePanel adaptivePanel2;
    private widgets.button.MainMenuButton appearanceButton;
    private widgets.button.MainMenuButton blockedButton;
    private widgets.panel.AdaptivePanel bottomPanel;
    private widgets.panel.AdaptivePanel contentPanel;
    private widgets.button.MainMenuButton generalButton;
    private widgets.button.MainMenuButton historyButton;
    private javax.swing.JPanel jPanel1;
    private widgets.panel.AdaptivePanel maniMenuPanel;
    private widgets.panel.AdaptivePanel menuPanel;
    private widgets.button.MainMenuButton notificationsButton;
    private widgets.button.AdaptiveButton settingsButton;
    private widgets.panel.AdaptivePanel spacePanel;
    private widgets.panel.AdaptivePanel tabbedPanel;
    // End of variables declaration//GEN-END:variables
}
