/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NoDisabilityMainView.java
 *
 * Created on 23 Νοε 2011, 3:56:11 μμ
 */
package assignment2.NoDisability;

import assignment2.Contact;

/**
 *
 * @author koutsop
 */
public class NoDisabilityMainView extends javax.swing.JPanel {

    /** Creates new form NoDisabilityMainView */
    public NoDisabilityMainView() {
        initComponents();
		AddContacts();
    }
	
	private void AddContacts () {
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
//		contactsPanel.add(new Contact("ContactImg", "StatusImg", "Koutsopoulos Nikolaos", "H zwh einai skata"));
		
	}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new widgets.panel.AdaptivePanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contactsPanel = new widgets.panel.AdaptivePanel();
        adaptiveButton5 = new widgets.button.AdaptiveButton();
        adaptiveButton6 = new widgets.button.AdaptiveButton();
        adaptiveButton7 = new widgets.button.AdaptiveButton();
        adaptiveButton8 = new widgets.button.AdaptiveButton();
        adaptiveButton9 = new widgets.button.AdaptiveButton();
        adaptiveButton10 = new widgets.button.AdaptiveButton();
        adaptiveButton12 = new widgets.button.AdaptiveButton();
        adaptiveButton13 = new widgets.button.AdaptiveButton();
        adaptiveButton14 = new widgets.button.AdaptiveButton();
        menuPanel = new widgets.panel.AdaptivePanel();
        adaptiveButton1 = new widgets.button.AdaptiveButton();
        adaptiveButton2 = new widgets.button.AdaptiveButton();
        adaptiveButton3 = new widgets.button.AdaptiveButton();
        adaptiveButton4 = new widgets.button.AdaptiveButton();
        contentPanel = new widgets.panel.AdaptivePanel();
        adaptiveButton11 = new widgets.button.AdaptiveButton();

        setLayout(new java.awt.BorderLayout());

        leftPanel.setLayout(new javax.swing.BoxLayout(leftPanel, javax.swing.BoxLayout.PAGE_AXIS));

        contactsPanel.setLayout(new javax.swing.BoxLayout(contactsPanel, javax.swing.BoxLayout.PAGE_AXIS));

        adaptiveButton5.setText("adaptiveButton5");
        contactsPanel.add(adaptiveButton5);

        adaptiveButton6.setText("adaptiveButton6");
        contactsPanel.add(adaptiveButton6);

        adaptiveButton7.setText("adaptiveButton7");
        contactsPanel.add(adaptiveButton7);

        adaptiveButton8.setText("adaptiveButton8");
        contactsPanel.add(adaptiveButton8);

        adaptiveButton9.setText("adaptiveButton9");
        contactsPanel.add(adaptiveButton9);

        adaptiveButton10.setText("adaptiveButton10");
        contactsPanel.add(adaptiveButton10);

        adaptiveButton12.setText("adaptiveButton12");
        contactsPanel.add(adaptiveButton12);

        adaptiveButton13.setText("adaptiveButton13");
        contactsPanel.add(adaptiveButton13);

        adaptiveButton14.setText("adaptiveButton14");
        contactsPanel.add(adaptiveButton14);

        jScrollPane1.setViewportView(contactsPanel);

        leftPanel.add(jScrollPane1);

        add(leftPanel, java.awt.BorderLayout.LINE_START);

        menuPanel.setLayout(new javax.swing.BoxLayout(menuPanel, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveButton1.setText("adaptiveButton1");
        menuPanel.add(adaptiveButton1);

        adaptiveButton2.setText("adaptiveButton2");
        menuPanel.add(adaptiveButton2);

        adaptiveButton3.setText("adaptiveButton3");
        menuPanel.add(adaptiveButton3);

        adaptiveButton4.setText("adaptiveButton4");
        menuPanel.add(adaptiveButton4);

        add(menuPanel, java.awt.BorderLayout.PAGE_START);

        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.LINE_AXIS));

        adaptiveButton11.setText("adaptiveButton11");
        contentPanel.add(adaptiveButton11);

        add(contentPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widgets.button.AdaptiveButton adaptiveButton1;
    private widgets.button.AdaptiveButton adaptiveButton10;
    private widgets.button.AdaptiveButton adaptiveButton11;
    private widgets.button.AdaptiveButton adaptiveButton12;
    private widgets.button.AdaptiveButton adaptiveButton13;
    private widgets.button.AdaptiveButton adaptiveButton14;
    private widgets.button.AdaptiveButton adaptiveButton2;
    private widgets.button.AdaptiveButton adaptiveButton3;
    private widgets.button.AdaptiveButton adaptiveButton4;
    private widgets.button.AdaptiveButton adaptiveButton5;
    private widgets.button.AdaptiveButton adaptiveButton6;
    private widgets.button.AdaptiveButton adaptiveButton7;
    private widgets.button.AdaptiveButton adaptiveButton8;
    private widgets.button.AdaptiveButton adaptiveButton9;
    private widgets.panel.AdaptivePanel contactsPanel;
    private widgets.panel.AdaptivePanel contentPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private widgets.panel.AdaptivePanel leftPanel;
    private widgets.panel.AdaptivePanel menuPanel;
    // End of variables declaration//GEN-END:variables
}
